param(
    [string]$MySqlUser = "root",
    [string]$MySqlPassword = "123456",
    [string]$Database = "fxl_game_local",
    [string]$OutFile = ""
)

$ErrorActionPreference = "Stop"
$Root = Resolve-Path (Join-Path $PSScriptRoot "..\..")
if (-not $OutFile) {
    $OutFile = Join-Path $Root "server\sql\local_min_schema.sql"
}

$dumpCandidates = @(
    "C:\Program Files\MySQL\MySQL Server 8.4\bin\mysqldump.exe",
    "C:\Program Files\MySQL\MySQL Server 8.0\bin\mysqldump.exe"
)
$dumpExe = $dumpCandidates | Where-Object { Test-Path $_ } | Select-Object -First 1
if (-not $dumpExe) { throw "mysqldump.exe not found" }

$tempDir = Join-Path $Root ".local\schema-export"
New-Item -ItemType Directory -Force -Path $tempDir | Out-Null
$tempFile = Join-Path $tempDir "schema.sql"
Remove-Item -LiteralPath $tempFile -Force -ErrorAction SilentlyContinue

$arguments = @(
    "--host=127.0.0.1",
    "--port=3306",
    "--user=$MySqlUser",
    "--password=$MySqlPassword",
    "--default-character-set=utf8mb4",
    "--no-data",
    "--skip-triggers",
    "--skip-add-drop-table",
    "--set-gtid-purged=OFF",
    "--result-file=$tempFile",
    $Database
)
& $dumpExe @arguments
if ($LASTEXITCODE -ne 0) { throw "mysqldump failed with exit code $LASTEXITCODE" }

$schema = Get-Content -LiteralPath $tempFile -Raw -Encoding UTF8
$schema = $schema -replace '(?m)^CREATE TABLE ', 'CREATE TABLE IF NOT EXISTS '
$schema = $schema -replace ' AUTO_INCREMENT=\d+', ''
$schema = $schema -replace '(?m)^-- Host:.*\r?\n', ''
$schema = $schema -replace '(?m)^-- Dump completed on .*\r?\n?', ''
$header = @"
-- Local Windows fallback schema exported from the verified local database.
-- Contains table structure only; never use this file as a production migration.
-- Generated by tools/local/Export-LocalSchema.ps1.

"@
$seed = @"

-- Local-only first-charge UI fallback. Do not treat these as production rewards.
INSERT INTO ``hd_peizhi_info``
  (``type``,``yb``,``count``,``lv``,``idx``,``cdTime``,``price``,``count_ext8``,``lastTime_ext32``,``zhenying1_name``,``zhenying2_name``,``water_cz``,``bug_cz``,``step1_cz``,``step2_cz``)
SELECT 29,60,1,0,1,0,6,0,0,'','',0,0,0,0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ``hd_peizhi_info`` WHERE ``type``=29);

INSERT INTO ``huodong_award``
  (``type``,``idx``,``YB``,``award1``,``num1``,``petQt1``,``petQtLv1``,``award2``,``num2``,``petQt2``,``petQtLv2``,``award3``,``num3``,``petQt3``,``petQtLv3``,``award4``,``num4``,``petQt4``,``petQtLv4``,``award5``,``num5``,``petQt5``,``petQtLv5``,``award6``,``num6``,``petQt6``,``petQtLv6``,``idx2``,``idx3``)
SELECT 29,1,0,60002,19,5,1,1001,10,0,0,837,10,0,0,60000,100000,0,0,60001,500,0,0,0,0,0,0,0,0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ``huodong_award`` WHERE ``type``=29 AND ``idx``=1);

-- Trading-house initialization requires one baseline exchange-rate row.
INSERT INTO ``jiaoyi_gold_yuzhi`` (``id``,``gold``,``time``)
SELECT 1,30000,NOW() FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ``jiaoyi_gold_yuzhi``);

-- Keep the local trading-house feature in its legacy default state.
INSERT INTO ``function_switch`` (``id``,``function_type``,``switch_state``)
SELECT 1,1,1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ``function_switch`` WHERE ``function_type``=1);
"@

[System.IO.File]::WriteAllText($OutFile, $header + $schema.TrimStart() + $seed, [System.Text.UTF8Encoding]::new($false))
Write-Host "Exported structure-only local schema: $OutFile"
