-- Local Windows fallback schema exported from the verified local database.
-- Contains table structure only; never use this file as a production migration.
-- Generated by tools/local/Export-LocalSchema.ps1.
-- MySQL dump 10.13  Distrib 8.4.9, for Win64 (x86_64)
--
-- ------------------------------------------------------
-- Server version	8.4.9

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `admin`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `admin` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `allows`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `allows` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `another`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `another` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `arena_log`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `arena_log` (
  `id` int NOT NULL AUTO_INCREMENT,
  `role1_id` int NOT NULL DEFAULT '0',
  `type1` tinyint NOT NULL DEFAULT '0',
  `role1_name` varchar(32) NOT NULL DEFAULT '',
  `role1_head` tinyint NOT NULL DEFAULT '0',
  `role1_lv` int NOT NULL DEFAULT '0',
  `role1_vip` tinyint NOT NULL DEFAULT '0',
  `role1_power` bigint NOT NULL DEFAULT '0',
  `role2_id` int NOT NULL DEFAULT '0',
  `type2` tinyint NOT NULL DEFAULT '0',
  `role2_name` varchar(32) NOT NULL DEFAULT '',
  `role2_head` tinyint NOT NULL DEFAULT '0',
  `role2_lv` int NOT NULL DEFAULT '0',
  `role2_vip` tinyint NOT NULL DEFAULT '0',
  `role2_power` bigint NOT NULL DEFAULT '0',
  `result` int NOT NULL DEFAULT '0',
  `rank1` int NOT NULL DEFAULT '0',
  `rank2` int NOT NULL DEFAULT '0',
  `time` int NOT NULL DEFAULT '0',
  `fightdata` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `rank1` (`rank1`),
  KEY `rank2` (`rank2`),
  KEY `time` (`time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `arena_paihang`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `arena_paihang` (
  `rank` int NOT NULL AUTO_INCREMENT,
  `robot` smallint NOT NULL DEFAULT '0',
  `role_id` int NOT NULL DEFAULT '0',
  `win_num` int NOT NULL DEFAULT '0',
  `up_down` int NOT NULL DEFAULT '0',
  `jiangli` int NOT NULL DEFAULT '0',
  `name` varchar(32) NOT NULL DEFAULT '',
  `level` int NOT NULL DEFAULT '0',
  `vip_lv` smallint NOT NULL DEFAULT '0',
  `xiang` int NOT NULL DEFAULT '0',
  `mount_id` int NOT NULL DEFAULT '0',
  `wing_id` int NOT NULL DEFAULT '0',
  `wuqi` int NOT NULL DEFAULT '0',
  `lighteffect` int NOT NULL DEFAULT '0',
  `shenqi` int NOT NULL DEFAULT '0',
  `bow_count` int NOT NULL DEFAULT '0',
  `egg_count` int NOT NULL DEFAULT '0',
  `act_time` int NOT NULL DEFAULT '0',
  UNIQUE KEY `rank_2` (`rank`),
  KEY `jiangli` (`jiangli`),
  KEY `robot` (`robot`),
  KEY `role_id` (`role_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 ROW_FORMAT=DYNAMIC;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `arena_paihang_save`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `arena_paihang_save` (
  `rank` int NOT NULL AUTO_INCREMENT,
  `robot` smallint NOT NULL DEFAULT '0',
  `role_id` int NOT NULL DEFAULT '0',
  `win_num` int NOT NULL DEFAULT '0',
  `up_down` int NOT NULL DEFAULT '0',
  `jiangli` int NOT NULL DEFAULT '0',
  `name` varchar(32) NOT NULL DEFAULT '',
  `level` int NOT NULL DEFAULT '0',
  `vip_lv` smallint NOT NULL DEFAULT '0',
  `xiang` int NOT NULL DEFAULT '0',
  `mount_id` int NOT NULL DEFAULT '0',
  `wing_id` int NOT NULL DEFAULT '0',
  `wuqi` int NOT NULL DEFAULT '0',
  `lighteffect` int NOT NULL DEFAULT '0',
  `shenqi` int NOT NULL DEFAULT '0',
  `bow_count` int NOT NULL DEFAULT '0',
  `egg_count` int NOT NULL DEFAULT '0',
  `act_time` int NOT NULL DEFAULT '0',
  UNIQUE KEY `rank_2` (`rank`),
  KEY `jiangli` (`jiangli`),
  KEY `robot` (`robot`),
  KEY `role_id` (`role_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 ROW_FORMAT=DYNAMIC;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `arena_robot`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `arena_robot` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `array`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `array` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `ascii`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `ascii` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `back_libao_info`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `back_libao_info` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `bad`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `bad` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `bang_pai`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `bang_pai` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(64) NOT NULL DEFAULT '',
  `info` text,
  `level` int NOT NULL DEFAULT '1',
  `fanrong` int NOT NULL DEFAULT '0',
  `money` int NOT NULL DEFAULT '0',
  `kouhao` varchar(255) NOT NULL DEFAULT '',
  `gonggao` text,
  `title` int NOT NULL DEFAULT '0',
  `copy` text,
  `res2` int NOT NULL DEFAULT '0',
  `res3` int NOT NULL DEFAULT '0',
  `res4` int NOT NULL DEFAULT '0',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `activity` int NOT NULL DEFAULT '0',
  `gongXian` int NOT NULL DEFAULT '0',
  `exp` int NOT NULL DEFAULT '0',
  `fireState` int NOT NULL DEFAULT '0',
  `onFireTime` int NOT NULL DEFAULT '0',
  `robNum` int NOT NULL DEFAULT '0',
  `robExp` int NOT NULL DEFAULT '0',
  `treeExp` int NOT NULL DEFAULT '0',
  `prayExp` int NOT NULL DEFAULT '0',
  `treeLv` int NOT NULL DEFAULT '1',
  `prayNum` int NOT NULL DEFAULT '0',
  `addTreeExpTime` int NOT NULL DEFAULT '0',
  `memberReward` text,
  `treeTotalExp` int NOT NULL DEFAULT '0',
  `bz_jifen` int NOT NULL DEFAULT '0',
  `xianzhun_lv` int NOT NULL DEFAULT '0',
  `yingxiangli` int NOT NULL DEFAULT '0',
  `shangxian_info` text,
  `mission` text,
  `juanxian_rank` text,
  `auto_limit_lv` int NOT NULL DEFAULT '0',
  `huoyue` int NOT NULL DEFAULT '0',
  `lianqi_lv` text,
  `skills` text,
  `state` int NOT NULL DEFAULT '1',
  `rank` int NOT NULL DEFAULT '1',
  `pic` int NOT NULL DEFAULT '0',
  `chuanwei` int NOT NULL DEFAULT '0',
  `jiesan_time` int NOT NULL DEFAULT '0',
  `del_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `state` (`state`),
  KEY `level` (`level`),
  KEY `exp` (`exp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `bang_pai_guard`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `bang_pai_guard` (
  `id` int NOT NULL AUTO_INCREMENT,
  `bang_id` int NOT NULL DEFAULT '0',
  `guardIdx` int NOT NULL DEFAULT '0',
  `role_id` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `bang_pai_log`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `bang_pai_log` (
  `id` int NOT NULL AUTO_INCREMENT,
  `bang_id` int NOT NULL DEFAULT '0',
  `role_id` int NOT NULL DEFAULT '0',
  `type` int NOT NULL DEFAULT '0',
  `msg` text,
  `msg2` text,
  `time` int NOT NULL DEFAULT '0',
  `time_str` varchar(32) NOT NULL DEFAULT '',
  `tar_bang_id` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `bang_pai_mission`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `bang_pai_mission` (
  `id` int NOT NULL AUTO_INCREMENT,
  `award1` mediumtext,
  `award2` mediumtext,
  `desc_str` mediumtext,
  `name` mediumtext,
  `num1` mediumtext,
  `num2` mediumtext,
  `type` mediumtext,
  `value` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `bang_pai_plant`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `bang_pai_plant` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `bang_pai_role`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `bang_pai_role` (
  `id` int NOT NULL AUTO_INCREMENT,
  `bangpai_id` int NOT NULL DEFAULT '0',
  `role_id` int NOT NULL DEFAULT '0',
  `ank` int NOT NULL DEFAULT '4',
  `join_time` int NOT NULL DEFAULT '0',
  `total_bangGong` int NOT NULL DEFAULT '0',
  `huoyue` int NOT NULL DEFAULT '0',
  `rank` int NOT NULL DEFAULT '4',
  PRIMARY KEY (`id`),
  KEY `bangpai_id` (`bangpai_id`),
  KEY `role_id` (`role_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `bang_pai_seed_config`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `bang_pai_seed_config` (
  `id` int NOT NULL AUTO_INCREMENT,
  `gainItem` mediumtext,
  `gainType` mediumtext,
  `gainValue` mediumtext,
  `itemId` mediumtext,
  `killBugLimit` mediumtext,
  `killBugTimeGap` mediumtext,
  `pic1` mediumtext,
  `pic2` mediumtext,
  `pic3` mediumtext,
  `price` mediumtext,
  `priceType` mediumtext,
  `ripeTimeGap` mediumtext,
  `stealNum` mediumtext,
  `treeName` mediumtext,
  `wateringLimit` mediumtext,
  `wateringReduce` mediumtext,
  `wateringTimeGap` mediumtext,
  `witheredTimeGap` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `bang_pai_shangxian`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `bang_pai_shangxian` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(64) NOT NULL DEFAULT '',
  `bangpai_id` int NOT NULL DEFAULT '0',
  `qin_mi` int NOT NULL DEFAULT '0',
  `add_type` int NOT NULL DEFAULT '0',
  `add_value` int NOT NULL DEFAULT '0',
  `gift_item_id` int NOT NULL DEFAULT '0',
  `gift_item_num` int NOT NULL DEFAULT '0',
  `gift_banggong` int NOT NULL DEFAULT '0',
  `src_bangpai_id` int NOT NULL DEFAULT '0',
  `lalong_time` int NOT NULL DEFAULT '0',
  `timer_time` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `bang_pai_shangxian_mode`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `bang_pai_shangxian_mode` (
  `id` int NOT NULL AUTO_INCREMENT,
  `gain_type1` mediumtext,
  `gain_type2` mediumtext,
  `gain_value1` mediumtext,
  `gain_value2` mediumtext,
  `loss_type` mediumtext,
  `loss_value` mediumtext,
  `name` mediumtext,
  `succ_ratio` mediumtext,
  `type` mediumtext,
  `use_item_id1` mediumtext,
  `use_item_id2` mediumtext,
  `use_item_num1` mediumtext,
  `use_item_num2` mediumtext,
  `vip_limit` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `bang_tiaozhan`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `bang_tiaozhan` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `bangzhan`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `bangzhan` (
  `id` int NOT NULL AUTO_INCREMENT,
  `bangpai_id` int NOT NULL DEFAULT '0',
  `group` int NOT NULL DEFAULT '0',
  `type` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `bangpai_id` (`bangpai_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `bangzhan_role`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `bangzhan_role` (
  `id` int NOT NULL AUTO_INCREMENT,
  `role_id` int NOT NULL DEFAULT '0',
  `bang_id` int NOT NULL DEFAULT '0',
  `role_name` varchar(32) NOT NULL DEFAULT '',
  `jifen` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `role_id` (`role_id`),
  KEY `bang_id` (`bang_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `black_ip`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `black_ip` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `boost`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `boost` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `chat_ignore_word`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `chat_ignore_word` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `chat_log`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `chat_log` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `chong_fanli`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `chong_fanli` (
  `id` int NOT NULL AUTO_INCREMENT,
  `chongzhi` mediumtext,
  `fanli` mediumtext,
  `first_fanli` mediumtext,
  `first_item_id` mediumtext,
  `first_item_num` mediumtext,
  `item_id` mediumtext,
  `item_num` mediumtext,
  `pic_idx` mediumtext,
  `show_idx` mediumtext,
  `type` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `chongfanli`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `chongfanli` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `config`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `config` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `consideration`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `consideration` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `cz_complete`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `cz_complete` (
  `id` int NOT NULL AUTO_INCREMENT,
  `ad` mediumtext,
  `card_num` mediumtext,
  `err_msg` mediumtext,
  `is_deal` mediumtext,
  `money` mediumtext,
  `role_id` mediumtext,
  `role_level` mediumtext,
  `role_name` mediumtext,
  `server_id` mediumtext,
  `state` mediumtext,
  `time` mediumtext,
  `type` mediumtext,
  `user_id` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `cz_notice`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `cz_notice` (
  `id` int NOT NULL AUTO_INCREMENT,
  `is_first` mediumtext,
  `money` mediumtext,
  `msg` mediumtext,
  `user_id` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `cz_to_other_reward`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `cz_to_other_reward` (
  `id` int NOT NULL AUTO_INCREMENT,
  `RMB` int NOT NULL DEFAULT '0',
  `self_award1` int NOT NULL DEFAULT '0',
  `self_num1` int NOT NULL DEFAULT '0',
  `self_award2` int NOT NULL DEFAULT '0',
  `self_num2` int NOT NULL DEFAULT '0',
  `self_award3` int NOT NULL DEFAULT '0',
  `self_num3` int NOT NULL DEFAULT '0',
  `self_award4` int NOT NULL DEFAULT '0',
  `self_num4` int NOT NULL DEFAULT '0',
  `f_award1` int NOT NULL DEFAULT '0',
  `f_num1` int NOT NULL DEFAULT '0',
  `f_award2` int NOT NULL DEFAULT '0',
  `f_num2` int NOT NULL DEFAULT '0',
  `f_award3` int NOT NULL DEFAULT '0',
  `f_num3` int NOT NULL DEFAULT '0',
  `f_award4` int NOT NULL DEFAULT '0',
  `f_num4` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `dailysign`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `dailysign` (
  `id` int NOT NULL AUTO_INCREMENT,
  `_1` mediumtext,
  `award_num` mediumtext,
  `award_type` mediumtext,
  `award_value` mediumtext,
  `day_idx` mediumtext,
  `mon_type` mediumtext,
  `vip_lv` mediumtext,
  `vip_multiple` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `defining`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `defining` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `dengjilibao`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `dengjilibao` (
  `id` int NOT NULL AUTO_INCREMENT,
  `goods1` mediumtext,
  `goods2` mediumtext,
  `goods3` mediumtext,
  `level` mediumtext,
  `num1` mediumtext,
  `num2` mediumtext,
  `num3` mediumtext,
  `value1` mediumtext,
  `value2` mediumtext,
  `value3` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `doxygen`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `doxygen` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `encoding`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `encoding` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `equip`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `equip` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `fabao`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `fabao` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `fanli_jihuoma`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `fanli_jihuoma` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `festival_award`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `festival_award` (
  `id` int NOT NULL AUTO_INCREMENT,
  `type` int NOT NULL DEFAULT '0',
  `start_id` int NOT NULL DEFAULT '0',
  `end_id` int NOT NULL DEFAULT '0',
  `score` int NOT NULL DEFAULT '0',
  `idx` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `festival_box`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `festival_box` (
  `id` int NOT NULL AUTO_INCREMENT,
  `box_id` int NOT NULL DEFAULT '0',
  `item_id` int NOT NULL DEFAULT '0',
  `odds` int NOT NULL DEFAULT '0',
  `num` int NOT NULL DEFAULT '0',
  `quality` int NOT NULL DEFAULT '0',
  `quality_level` int NOT NULL DEFAULT '0',
  `isnotice` int NOT NULL DEFAULT '0',
  `day_limit` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `box_id` (`box_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `festival_record`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `festival_record` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `fight_cg`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `fight_cg` (
  `id` int NOT NULL AUTO_INCREMENT,
  `fightMsg` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `fight_playback`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `fight_playback` (
  `id` int NOT NULL AUTO_INCREMENT,
  `type` int NOT NULL DEFAULT '0',
  `role_id` int NOT NULL DEFAULT '0',
  `tar_role_id` int NOT NULL DEFAULT '0',
  `fightMsg` mediumtext NOT NULL,
  `notice` varchar(256) NOT NULL DEFAULT '',
  `time` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `flower_config`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `flower_config` (
  `id` int NOT NULL AUTO_INCREMENT,
  `buy_type` mediumtext,
  `item_id` mediumtext,
  `mei_li` mediumtext,
  `price` mediumtext,
  `qin_mi` mediumtext,
  `rank` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `footprint_config`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `footprint_config` (
  `id` int NOT NULL AUTO_INCREMENT,
  `buy_type` mediumtext,
  `desc` mediumtext,
  `name` mediumtext,
  `price` mediumtext,
  `rank` mediumtext,
  `time` mediumtext,
  `item` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `friend_list`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `friend_list` (
  `id` int NOT NULL AUTO_INCREMENT,
  `role_id` int NOT NULL,
  `friend_info` text NOT NULL,
  `apply_list` text NOT NULL,
  `black_list` text NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `role_id` (`role_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `friend_list_save`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `friend_list_save` (
  `id` int NOT NULL AUTO_INCREMENT,
  `role_id` int NOT NULL,
  `friend_info` text NOT NULL,
  `apply_list` text NOT NULL,
  `black_list` text NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `role_id` (`role_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `fuben_richang`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `fuben_richang` (
  `id` int NOT NULL AUTO_INCREMENT,
  `condes1` mediumtext,
  `condes2` mediumtext,
  `condes3` mediumtext,
  `condes4` mediumtext,
  `desc_ratio` mediumtext,
  `desc_ratio1` mediumtext,
  `desc_title` mediumtext,
  `enterlimit` mediumtext,
  `extdata8` mediumtext,
  `fuben_index` mediumtext,
  `isShow` mediumtext,
  `level` mediumtext,
  `lvup_type1` mediumtext,
  `lvup_type2` mediumtext,
  `lvup_type3` mediumtext,
  `lvup_type4` mediumtext,
  `lvup_value1` mediumtext,
  `lvup_value2` mediumtext,
  `lvup_value3` mediumtext,
  `lvup_value4` mediumtext,
  `mobs` mediumtext,
  `mop_time` mediumtext,
  `name` mediumtext,
  `reward1` mediumtext,
  `reward2` mediumtext,
  `reward3` mediumtext,
  `reward4` mediumtext,
  `sceneId` mediumtext,
  `tili` mediumtext,
  `type` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `function_switch`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `function_switch` (
  `id` int NOT NULL AUTO_INCREMENT,
  `function_type` int NOT NULL DEFAULT '0',
  `switch_state` int NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `function_type` (`function_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `game_scene`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `game_scene` (
  `id` int NOT NULL AUTO_INCREMENT,
  `fight_step` mediumtext,
  `fight_type` mediumtext,
  `group_id` mediumtext,
  `height` mediumtext,
  `map_id` mediumtext,
  `monster` mediumtext,
  `name` mediumtext,
  `show_type` mediumtext,
  `width` mediumtext,
  `world_trans` mediumtext,
  `x` mediumtext,
  `y` mediumtext,
  `pai_ming` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `genericreader`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `genericreader` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `genericvalue`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `genericvalue` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `global_variable`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `global_variable` (
  `id` int NOT NULL,
  `value` int NOT NULL DEFAULT '0',
  `data` text,
  `time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `happening`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `happening` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `hd_7ridenglu`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `hd_7ridenglu` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `hd_bang_goods`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `hd_bang_goods` (
  `id` int NOT NULL AUTO_INCREMENT,
  `award1` mediumtext,
  `pic` mediumtext,
  `score1_get` mediumtext,
  `score1_give` mediumtext,
  `award2` int NOT NULL DEFAULT '0',
  `score2_give` int NOT NULL DEFAULT '0',
  `score2_get` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `hd_chou_record`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `hd_chou_record` (
  `id` int NOT NULL AUTO_INCREMENT,
  `role_id` int NOT NULL DEFAULT '0',
  `role_name` varchar(64) NOT NULL DEFAULT '',
  `time` datetime DEFAULT NULL,
  `award` int NOT NULL DEFAULT '0',
  `level` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `hd_exchange_drop`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `hd_exchange_drop` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `hd_exchange_list`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `hd_exchange_list` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `hd_paihang_info`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `hd_paihang_info` (
  `id` int NOT NULL AUTO_INCREMENT,
  `huodong_type` int NOT NULL DEFAULT '0',
  `start_id` int NOT NULL DEFAULT '0',
  `end_id` int NOT NULL DEFAULT '0',
  `idx` int NOT NULL DEFAULT '0',
  `score` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `hd_paihang_record`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `hd_paihang_record` (
  `id` int NOT NULL AUTO_INCREMENT,
  `huodong_type` int NOT NULL DEFAULT '0',
  `role_id` int NOT NULL DEFAULT '0',
  `role_name` varchar(64) NOT NULL DEFAULT '',
  `bangpai_name` varchar(64) NOT NULL DEFAULT '',
  `data` int NOT NULL DEFAULT '0',
  `role_lv` int NOT NULL DEFAULT '0',
  `role_zhandouli` int NOT NULL DEFAULT '0',
  `time` int NOT NULL DEFAULT '0',
  `xiang` int NOT NULL DEFAULT '0',
  `sex` int NOT NULL DEFAULT '0',
  `rank` int NOT NULL DEFAULT '0',
  `start_time` int NOT NULL DEFAULT '0',
  `send_award` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `hd_peizhi_info`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `hd_peizhi_info` (
  `id` int NOT NULL AUTO_INCREMENT,
  `bug_cz` mediumtext,
  `cdTime` mediumtext,
  `count` mediumtext,
  `count_ext8` mediumtext,
  `idx` mediumtext,
  `lastTime_ext32` mediumtext,
  `lv` mediumtext,
  `price` mediumtext,
  `step1_cz` mediumtext,
  `step2_cz` mediumtext,
  `type` mediumtext,
  `water_cz` mediumtext,
  `yb` mediumtext,
  `zhenying1_name` mediumtext,
  `zhenying2_name` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `hd_rand_award`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `hd_rand_award` (
  `id` int NOT NULL AUTO_INCREMENT,
  `huodong_type` int NOT NULL DEFAULT '0',
  `award` int NOT NULL DEFAULT '0',
  `num` int NOT NULL DEFAULT '0',
  `petQt` int NOT NULL DEFAULT '0',
  `petQtLv` int NOT NULL DEFAULT '0',
  `rate` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `hd_save_data`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `hd_save_data` (
  `id` int NOT NULL AUTO_INCREMENT,
  `hd_type` int NOT NULL DEFAULT '0',
  `save_data` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `hd_show_log`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `hd_show_log` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `help`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `help` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `huan_haoli_drop`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `huan_haoli_drop` (
  `id` int NOT NULL AUTO_INCREMENT,
  `ext8_idx` mediumtext,
  `item_id` mediumtext,
  `limit_num` mediumtext,
  `name` mediumtext,
  `type` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `huodong_award`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `huodong_award` (
  `id` int NOT NULL AUTO_INCREMENT,
  `award1` mediumtext,
  `award2` mediumtext,
  `award3` mediumtext,
  `award4` mediumtext,
  `award5` mediumtext,
  `award6` mediumtext,
  `idx` mediumtext,
  `idx2` mediumtext,
  `idx3` mediumtext,
  `num1` mediumtext,
  `num2` mediumtext,
  `num3` mediumtext,
  `num4` mediumtext,
  `num5` mediumtext,
  `num6` mediumtext,
  `petQt1` mediumtext,
  `petQt2` mediumtext,
  `petQt3` mediumtext,
  `petQt4` mediumtext,
  `petQt5` mediumtext,
  `petQt6` mediumtext,
  `petQtLv1` mediumtext,
  `petQtLv2` mediumtext,
  `petQtLv3` mediumtext,
  `petQtLv4` mediumtext,
  `petQtLv5` mediumtext,
  `petQtLv6` mediumtext,
  `type` mediumtext,
  `YB` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `huodong_exchange`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `huodong_exchange` (
  `id` int NOT NULL AUTO_INCREMENT,
  `award1` mediumtext,
  `award2` mediumtext,
  `award3` mediumtext,
  `award4` mediumtext,
  `award5` mediumtext,
  `award6` mediumtext,
  `exchange_num_limit` mediumtext,
  `idx` mediumtext,
  `isShow` mediumtext,
  `material_1` mediumtext,
  `material_1_num` mediumtext,
  `material_2` mediumtext,
  `material_2_num` mediumtext,
  `material_3` mediumtext,
  `material_3_num` mediumtext,
  `material_4` mediumtext,
  `material_4_num` mediumtext,
  `material_5` mediumtext,
  `material_5_num` mediumtext,
  `material_is_or` mediumtext,
  `num1` mediumtext,
  `num2` mediumtext,
  `num3` mediumtext,
  `num4` mediumtext,
  `num5` mediumtext,
  `num6` mediumtext,
  `petQt1` mediumtext,
  `petQt2` mediumtext,
  `petQt3` mediumtext,
  `petQt4` mediumtext,
  `petQt5` mediumtext,
  `petQt6` mediumtext,
  `petQtLv1` mediumtext,
  `petQtLv2` mediumtext,
  `petQtLv3` mediumtext,
  `petQtLv4` mediumtext,
  `petQtLv5` mediumtext,
  `petQtLv6` mediumtext,
  `saveExt8` mediumtext,
  `type` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `huodong_exp`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `huodong_exp` (
  `id` int NOT NULL AUTO_INCREMENT,
  `exp1` mediumtext,
  `exp10` mediumtext,
  `exp100` mediumtext,
  `exp101` mediumtext,
  `exp102` mediumtext,
  `exp103` mediumtext,
  `exp104` mediumtext,
  `exp105` mediumtext,
  `exp106` mediumtext,
  `exp107` mediumtext,
  `exp108` mediumtext,
  `exp109` mediumtext,
  `exp11` mediumtext,
  `exp110` mediumtext,
  `exp111` mediumtext,
  `exp112` mediumtext,
  `exp113` mediumtext,
  `exp114` mediumtext,
  `exp115` mediumtext,
  `exp116` mediumtext,
  `exp117` mediumtext,
  `exp118` mediumtext,
  `exp119` mediumtext,
  `exp12` mediumtext,
  `exp120` mediumtext,
  `exp121` mediumtext,
  `exp122` mediumtext,
  `exp123` mediumtext,
  `exp124` mediumtext,
  `exp125` mediumtext,
  `exp126` mediumtext,
  `exp127` mediumtext,
  `exp128` mediumtext,
  `exp129` mediumtext,
  `exp13` mediumtext,
  `exp130` mediumtext,
  `exp14` mediumtext,
  `exp15` mediumtext,
  `exp16` mediumtext,
  `exp17` mediumtext,
  `exp18` mediumtext,
  `exp19` mediumtext,
  `exp2` mediumtext,
  `exp20` mediumtext,
  `exp21` mediumtext,
  `exp22` mediumtext,
  `exp23` mediumtext,
  `exp24` mediumtext,
  `exp25` mediumtext,
  `exp26` mediumtext,
  `exp27` mediumtext,
  `exp28` mediumtext,
  `exp29` mediumtext,
  `exp3` mediumtext,
  `exp30` mediumtext,
  `exp31` mediumtext,
  `exp32` mediumtext,
  `exp33` mediumtext,
  `exp34` mediumtext,
  `exp35` mediumtext,
  `exp36` mediumtext,
  `exp37` mediumtext,
  `exp38` mediumtext,
  `exp39` mediumtext,
  `exp4` mediumtext,
  `exp40` mediumtext,
  `exp41` mediumtext,
  `exp42` mediumtext,
  `exp43` mediumtext,
  `exp44` mediumtext,
  `exp45` mediumtext,
  `exp46` mediumtext,
  `exp47` mediumtext,
  `exp48` mediumtext,
  `exp49` mediumtext,
  `exp5` mediumtext,
  `exp50` mediumtext,
  `exp51` mediumtext,
  `exp52` mediumtext,
  `exp53` mediumtext,
  `exp54` mediumtext,
  `exp55` mediumtext,
  `exp56` mediumtext,
  `exp57` mediumtext,
  `exp58` mediumtext,
  `exp59` mediumtext,
  `exp6` mediumtext,
  `exp60` mediumtext,
  `exp61` mediumtext,
  `exp62` mediumtext,
  `exp63` mediumtext,
  `exp64` mediumtext,
  `exp65` mediumtext,
  `exp66` mediumtext,
  `exp67` mediumtext,
  `exp68` mediumtext,
  `exp69` mediumtext,
  `exp7` mediumtext,
  `exp70` mediumtext,
  `exp71` mediumtext,
  `exp72` mediumtext,
  `exp73` mediumtext,
  `exp74` mediumtext,
  `exp75` mediumtext,
  `exp76` mediumtext,
  `exp77` mediumtext,
  `exp78` mediumtext,
  `exp79` mediumtext,
  `exp8` mediumtext,
  `exp80` mediumtext,
  `exp81` mediumtext,
  `exp82` mediumtext,
  `exp83` mediumtext,
  `exp84` mediumtext,
  `exp85` mediumtext,
  `exp86` mediumtext,
  `exp87` mediumtext,
  `exp88` mediumtext,
  `exp89` mediumtext,
  `exp9` mediumtext,
  `exp90` mediumtext,
  `exp91` mediumtext,
  `exp92` mediumtext,
  `exp93` mediumtext,
  `exp94` mediumtext,
  `exp95` mediumtext,
  `exp96` mediumtext,
  `exp97` mediumtext,
  `exp98` mediumtext,
  `exp99` mediumtext,
  `name` mediumtext,
  `type` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `huodong_info`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `huodong_info` (
  `id` int NOT NULL AUTO_INCREMENT,
  `day` mediumtext,
  `endHour` mediumtext,
  `endTime` mediumtext,
  `isShow` mediumtext,
  `name` mediumtext,
  `pic` mediumtext,
  `showIdx` mediumtext,
  `startHour` mediumtext,
  `startTime` mediumtext,
  `type` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `huodong_time`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `huodong_time` (
  `id` int NOT NULL AUTO_INCREMENT,
  `beilv` int NOT NULL DEFAULT '1',
  `begin_time` timestamp NULL DEFAULT NULL,
  `end_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `input`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `input` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `integer`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `integer` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `item`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `item` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `des` varchar(256) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `pic` int NOT NULL,
  `quality` int NOT NULL DEFAULT '0',
  `type` int NOT NULL,
  `use_type` int NOT NULL,
  `sub_value` varchar(256) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `limit_lv` int NOT NULL,
  `limit_time` varchar(256) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `sell` int NOT NULL,
  `sort_priority` int NOT NULL DEFAULT '1',
  `jiage` int NOT NULL,
  `item_from` varchar(256) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `item_source` varchar(256) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `script` int NOT NULL,
  `use_jump` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `sort_priority` (`sort_priority`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin ROW_FORMAT=DYNAMIC;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `item_score_exchange`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `item_score_exchange` (
  `id` int NOT NULL AUTO_INCREMENT,
  `item_id` int NOT NULL DEFAULT '0',
  `score_give` int NOT NULL DEFAULT '0',
  `score_get` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `item_template`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `item_template` (
  `id` int NOT NULL AUTO_INCREMENT,
  `add_qixue` mediumtext,
  `add_sudu` mediumtext,
  `baoji` mediumtext,
  `des` mediumtext,
  `equip_pos` mediumtext,
  `fafang` mediumtext,
  `fangyu` mediumtext,
  `gongji` mediumtext,
  `item_from` mediumtext,
  `item_source` mediumtext,
  `jiage` mediumtext,
  `kangbao` mediumtext,
  `level` mediumtext,
  `mingzhong` mediumtext,
  `mod` mediumtext,
  `naijiu` mediumtext,
  `name` mediumtext,
  `pic` mediumtext,
  `quality` mediumtext,
  `sell` mediumtext,
  `sex` mediumtext,
  `shanbi` mediumtext,
  `sort_priority` mediumtext,
  `type` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `iterator`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `iterator` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `jiaoyi_gold_yuzhi`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `jiaoyi_gold_yuzhi` (
  `id` int NOT NULL AUTO_INCREMENT,
  `gold` int NOT NULL DEFAULT '30000',
  `time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `jiaoyi_info`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `jiaoyi_info` (
  `id` int NOT NULL AUTO_INCREMENT,
  `time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `seller_id` int NOT NULL DEFAULT '0',
  `seller_name` varchar(32) NOT NULL DEFAULT '',
  `sell_yb` int NOT NULL DEFAULT '0',
  `buy_gold` int NOT NULL DEFAULT '0',
  `already_sell_yb` int NOT NULL DEFAULT '0',
  `state` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `state` (`state`),
  KEY `seller_id` (`seller_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `jiaoyi_record`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `jiaoyi_record` (
  `id` int NOT NULL AUTO_INCREMENT,
  `time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `seller_id` int NOT NULL DEFAULT '0',
  `seller_name` varchar(32) NOT NULL DEFAULT '',
  `buyer_id` int NOT NULL DEFAULT '0',
  `buyer_name` varchar(32) NOT NULL DEFAULT '',
  `sell_yb` int NOT NULL DEFAULT '0',
  `buy_gold` int NOT NULL DEFAULT '0',
  `state` int NOT NULL DEFAULT '0',
  `poundage` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `seller_id` (`seller_id`),
  KEY `buyer_id` (`buyer_id`),
  KEY `state` (`state`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `jihuoma`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `jihuoma` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `jihuoma_fa`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `jihuoma_fa` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `jump_point`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `jump_point` (
  `id` int NOT NULL AUTO_INCREMENT,
  `face` mediumtext,
  `from_scene` mediumtext,
  `from_x` mediumtext,
  `from_y` mediumtext,
  `to_scene` mediumtext,
  `to_x` mediumtext,
  `to_y` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `kf_config`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `kf_config` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `kuafu_1vs1_final_data`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `kuafu_1vs1_final_data` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `kuafu_1vs1_final_vote`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `kuafu_1vs1_final_vote` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `kuafu_1vs1_preliminary`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `kuafu_1vs1_preliminary` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `kuafu_paihang`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `kuafu_paihang` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `leitai_paiming`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `leitai_paiming` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `level_rank`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `level_rank` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `login_log_7`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `login_log_7` (
  `id` int NOT NULL AUTO_INCREMENT,
  `role_id` int NOT NULL,
  `level` smallint NOT NULL,
  `ad` int NOT NULL DEFAULT '0',
  `ip` varchar(128) NOT NULL,
  `net_info` varchar(128) NOT NULL,
  `mac` varchar(128) NOT NULL,
  `IMEI` varchar(128) NOT NULL,
  `IDFA` varchar(128) NOT NULL,
  `login_time` datetime NOT NULL,
  `logout_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `role_id` (`role_id`),
  KEY `ad` (`ad`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `mei_li_history`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `mei_li_history` (
  `id` int NOT NULL AUTO_INCREMENT,
  `round` int NOT NULL DEFAULT '0',
  `role_id` int NOT NULL DEFAULT '0',
  `name` varchar(64) NOT NULL DEFAULT '',
  `mei_li` int NOT NULL DEFAULT '0',
  `title` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `mei_li_paihang`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `mei_li_paihang` (
  `id` int NOT NULL AUTO_INCREMENT,
  `role_id` int NOT NULL DEFAULT '0',
  `name` varchar(64) NOT NULL DEFAULT '',
  `mei_li` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `mei_li_send_log`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `mei_li_send_log` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `microsoft`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `microsoft` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `mijing_boss_ratio`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `mijing_boss_ratio` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `mobai`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `mobai` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `money_giftbag_huodong`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `money_giftbag_huodong` (
  `id` int NOT NULL AUTO_INCREMENT,
  `hd_type` int NOT NULL DEFAULT '0',
  `gift_id` int NOT NULL DEFAULT '0',
  `gift_name` varchar(128) NOT NULL DEFAULT '',
  `money` int NOT NULL DEFAULT '0',
  `startTime` datetime DEFAULT NULL,
  `endTime` datetime DEFAULT NULL,
  `limit_buy_num` int NOT NULL DEFAULT '0',
  `limit_type` int NOT NULL DEFAULT '0',
  `limit_data1` int NOT NULL DEFAULT '0',
  `limit_data2` int NOT NULL DEFAULT '0',
  `award1` int NOT NULL DEFAULT '0',
  `num1` int NOT NULL DEFAULT '0',
  `petQt1` int NOT NULL DEFAULT '0',
  `petQtLv1` int NOT NULL DEFAULT '0',
  `award2` int NOT NULL DEFAULT '0',
  `num2` int NOT NULL DEFAULT '0',
  `petQt2` int NOT NULL DEFAULT '0',
  `petQtLv2` int NOT NULL DEFAULT '0',
  `award3` int NOT NULL DEFAULT '0',
  `num3` int NOT NULL DEFAULT '0',
  `petQt3` int NOT NULL DEFAULT '0',
  `petQtLv3` int NOT NULL DEFAULT '0',
  `pay_id` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `money_giftbag_pay`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `money_giftbag_pay` (
  `id` int NOT NULL AUTO_INCREMENT,
  `money` int NOT NULL DEFAULT '0',
  `ad` int NOT NULL DEFAULT '0',
  `pay_id` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `monster`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `monster` (
  `id` int NOT NULL AUTO_INCREMENT,
  `attack` mediumtext,
  `attackRatio` mediumtext,
  `attackStepRatio` mediumtext,
  `defence` mediumtext,
  `defenceRatio` mediumtext,
  `defenceStepRatio` mediumtext,
  `drop_item` mediumtext,
  `exp` mediumtext,
  `huanhua_material` mediumtext,
  `huanhuaPetId` mediumtext,
  `inTuJian` mediumtext,
  `isJueXingPet` mediumtext,
  `juexingPetId` mediumtext,
  `max_level` mediumtext,
  `max_quality` mediumtext,
  `maxHp` mediumtext,
  `maxHpRatio` mediumtext,
  `maxHpStepRatio` mediumtext,
  `min_level` mediumtext,
  `min_quality` mediumtext,
  `monsterName` mediumtext,
  `petName` mediumtext,
  `skill` mediumtext,
  `skillAttack` mediumtext,
  `skillAttackRatio` mediumtext,
  `skillAttackStepRatio` mediumtext,
  `speed` mediumtext,
  `speedRatio` mediumtext,
  `speedStepRatio` mediumtext,
  `t_drop_item` mediumtext,
  `tujianIdx` mediumtext,
  `type` mediumtext,
  `xiang` mediumtext,
  `zizhi` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `monster_boss_distribution`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `monster_boss_distribution` (
  `id` int NOT NULL AUTO_INCREMENT,
  `dropItem` mediumtext,
  `face` mediumtext,
  `fightPos1` mediumtext,
  `fightPos2` mediumtext,
  `fightPos3` mediumtext,
  `fightPos4` mediumtext,
  `fightPos5` mediumtext,
  `fightPos6` mediumtext,
  `meetDistance` mediumtext,
  `name` mediumtext,
  `pic` mediumtext,
  `pos_x` mediumtext,
  `pos_y` mediumtext,
  `radius` mediumtext,
  `sayContent` mediumtext,
  `scale1` mediumtext,
  `scale2` mediumtext,
  `scale3` mediumtext,
  `scale4` mediumtext,
  `scale5` mediumtext,
  `scale6` mediumtext,
  `sceneId` mediumtext,
  `step` mediumtext,
  `type` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `monster_distribution`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `monster_distribution` (
  `id` int NOT NULL AUTO_INCREMENT,
  `findPath_x` mediumtext,
  `findPath_y` mediumtext,
  `max_fightId` mediumtext,
  `meetDistance` mediumtext,
  `min_fightId` mediumtext,
  `monster_id` mediumtext,
  `pos` mediumtext,
  `radius` mediumtext,
  `scene_id` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `mutable`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `mutable` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `name_reg0`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `name_reg0` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `name_reg1`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `name_reg1` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `names`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `names` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `non`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `non` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `notice`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `notice` (
  `id` int NOT NULL AUTO_INCREMENT,
  `begin_time` mediumtext,
  `end_time` mediumtext,
  `msg` mediumtext,
  `time_space` mediumtext,
  `type` mediumtext,
  `type1` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `notice_login`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `notice_login` (
  `id` int NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL DEFAULT '',
  `msg` text,
  `showType` int NOT NULL DEFAULT '0',
  `jumpType` int NOT NULL DEFAULT '0',
  `beginTime` int NOT NULL DEFAULT '0',
  `endTime` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `npc_instance`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `npc_instance` (
  `id` int NOT NULL AUTO_INCREMENT,
  `face` mediumtext,
  `scene_id` mediumtext,
  `show_type` mediumtext,
  `template_id` mediumtext,
  `x_pos` mediumtext,
  `y_pos` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `npc_template`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `npc_template` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` mediumtext,
  `npc_type` mediumtext,
  `picture` mediumtext,
  `script` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `old_account`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `old_account` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `online_user_num`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `online_user_num` (
  `id` int NOT NULL AUTO_INCREMENT,
  `num` mediumtext,
  `time` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `operator`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `operator` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `parsestream`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `parsestream` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `plain`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `plain` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `pointer`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `pointer` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `pre`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `pre` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `predict`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `predict` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `primary`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `primary` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `qiang_hongbao_record`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `qiang_hongbao_record` (
  `id` int NOT NULL AUTO_INCREMENT,
  `role_id` int NOT NULL DEFAULT '0',
  `send_hb_count` int NOT NULL DEFAULT '0',
  `renqi_king_count` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `qin_mi_log`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `qin_mi_log` (
  `id` int NOT NULL AUTO_INCREMENT,
  `role1` int NOT NULL DEFAULT '0',
  `role2` int NOT NULL DEFAULT '0',
  `qin_mi` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `question`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `question` (
  `id` int NOT NULL AUTO_INCREMENT,
  `question` varchar(255) NOT NULL DEFAULT '',
  `answer1` varchar(255) NOT NULL DEFAULT '',
  `answer2` varchar(255) NOT NULL DEFAULT '',
  `answer3` varchar(255) NOT NULL DEFAULT '',
  `answer4` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `qunxian_paihang`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `qunxian_paihang` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `randombox_cfg`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `randombox_cfg` (
  `seq` int NOT NULL AUTO_INCREMENT,
  `box_id` int NOT NULL DEFAULT '0',
  `item_id` int NOT NULL DEFAULT '0',
  `odds` int NOT NULL DEFAULT '0',
  `id` int NOT NULL DEFAULT '0',
  `num` int NOT NULL DEFAULT '0',
  `quality` int NOT NULL DEFAULT '0',
  `quality_level` int NOT NULL DEFAULT '0',
  `isnotice` int NOT NULL DEFAULT '0',
  `day_limit` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`seq`),
  KEY `box_id` (`box_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `rank_list`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `rank_list` (
  `id` int NOT NULL AUTO_INCREMENT,
  `type` int NOT NULL DEFAULT '0',
  `rank` int NOT NULL DEFAULT '0',
  `role_id` int NOT NULL DEFAULT '0',
  `data1` bigint NOT NULL DEFAULT '0',
  `data2` bigint NOT NULL DEFAULT '0',
  `value1` int NOT NULL DEFAULT '0',
  `time` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `rank_list_save`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `rank_list_save` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `read`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `read` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `rob`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `rob` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `role_info`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `role_info` (
  `id` int NOT NULL AUTO_INCREMENT,
  `admin` mediumtext,
  `bank_item` mediumtext,
  `bd_money` mediumtext,
  `bitset` mediumtext,
  `chat_time` mediumtext,
  `exp` mediumtext,
  `head` mediumtext,
  `hots` mediumtext,
  `korea_money_gift` mediumtext,
  `kuafu_state` mediumtext,
  `level` mediumtext,
  `login_time` mediumtext,
  `model` mediumtext,
  `money` mediumtext,
  `mount` mediumtext,
  `name` mediumtext,
  `package` mediumtext,
  `pet` mediumtext,
  `pet_equip` mediumtext,
  `petZhanDouLi` mediumtext,
  `reg_time` mediumtext,
  `save_data` mediumtext,
  `sex` mediumtext,
  `sg_bitset` mediumtext,
  `shenqi` mediumtext,
  `state` mediumtext,
  `title` mediumtext,
  `user_book` mediumtext,
  `wing` mediumtext,
  `xianyuan` mediumtext,
  `zhanDouLi` mediumtext,
  `zhenfa` mediumtext,
  `save_val` mediumtext,
  `qianneng` mediumtext,
  `chat_channel` mediumtext,
  `bossFightStar` mediumtext,
  `mysteryShop` mediumtext,
  `xiuxian` mediumtext,
  `transform` mediumtext,
  `mission` mediumtext,
  `clientstring` mediumtext,
  `shenhunShop` mediumtext,
  `questIds` mediumtext,
  `find_res` mediumtext,
  `xunbao` mediumtext,
  `bang_skills` mediumtext,
  `guan_qia` mediumtext,
  `chou_ka` mediumtext,
  `blood_fight` mediumtext,
  `copyData` mediumtext,
  `user_spirit` mediumtext,
  `kuafu_1vs1` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `role_info_transfer`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `role_info_transfer` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `role_mirror`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `role_mirror` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `role_simple_list`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `role_simple_list` (
  `id` int NOT NULL,
  `name` varchar(32) NOT NULL DEFAULT '',
  `level` smallint NOT NULL DEFAULT '0',
  `power` bigint NOT NULL DEFAULT '0',
  `sex` tinyint NOT NULL DEFAULT '0',
  `head` smallint NOT NULL DEFAULT '0',
  `model` tinyint NOT NULL DEFAULT '0',
  `vipLv` tinyint NOT NULL DEFAULT '0',
  `bangId` int NOT NULL DEFAULT '0',
  `lastLoginTime` int NOT NULL DEFAULT '0',
  `huoyue_day` int NOT NULL DEFAULT '0',
  `huoyue_week` int NOT NULL DEFAULT '0',
  `jingJie` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `role_simple_list_save`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `role_simple_list_save` (
  `id` int NOT NULL,
  `name` varchar(32) NOT NULL DEFAULT '',
  `level` smallint NOT NULL DEFAULT '0',
  `power` bigint NOT NULL DEFAULT '0',
  `sex` tinyint NOT NULL DEFAULT '0',
  `head` smallint NOT NULL DEFAULT '0',
  `model` tinyint NOT NULL DEFAULT '0',
  `vipLv` tinyint NOT NULL DEFAULT '0',
  `bangId` int NOT NULL DEFAULT '0',
  `lastLoginTime` int NOT NULL DEFAULT '0',
  `huoyue_day` int NOT NULL DEFAULT '0',
  `huoyue_week` int NOT NULL DEFAULT '0',
  `jingJie` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `role_xiuxian`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `role_xiuxian` (
  `id` int NOT NULL AUTO_INCREMENT,
  `admin` mediumtext,
  `bangpai` mediumtext,
  `bank_item` mediumtext,
  `bank_money` mediumtext,
  `bitset` mediumtext,
  `bossFightStar` mediumtext,
  `chat_channel` mediumtext,
  `chat_time` mediumtext,
  `collect_npc` mediumtext,
  `currency` mediumtext,
  `daohang` mediumtext,
  `drop_touchitem` mediumtext,
  `equipment` mediumtext,
  `exp` mediumtext,
  `head` mediumtext,
  `hots` mediumtext,
  `hp` mediumtext,
  `jianyu_time` mediumtext,
  `level` mediumtext,
  `login_time` mediumtext,
  `map_id` mediumtext,
  `menpai` mediumtext,
  `money` mediumtext,
  `mount` mediumtext,
  `mp` mediumtext,
  `mp_gongxian` mediumtext,
  `mysteryShop` mediumtext,
  `name` mediumtext,
  `nextOpenTime` mediumtext,
  `open_pack` mediumtext,
  `package` mediumtext,
  `pet` mediumtext,
  `petKaiJia` mediumtext,
  `petZhanDouLi` mediumtext,
  `pk_time` mediumtext,
  `pk_val` mediumtext,
  `position` mediumtext,
  `qianneng` mediumtext,
  `reg_time` mediumtext,
  `save_data` mediumtext,
  `save_monster` mediumtext,
  `save_npc` mediumtext,
  `save_val` mediumtext,
  `script_double` mediumtext,
  `script_timer` mediumtext,
  `sex` mediumtext,
  `sg_bitset` mediumtext,
  `shop` mediumtext,
  `skills` mediumtext,
  `state` mediumtext,
  `tili` mediumtext,
  `title` mediumtext,
  `use_double_end` mediumtext,
  `use_double_type` mediumtext,
  `wing` mediumtext,
  `wing_zhandouli` mediumtext,
  `x_pos` mediumtext,
  `xiang` mediumtext,
  `y_pos` mediumtext,
  `zhanDouLi` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `script_save_role`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `script_save_role` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `server_list`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `server_list` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `shilian_robot`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `shilian_robot` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `shop`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `shop` (
  `id` int NOT NULL AUTO_INCREMENT,
  `item` int NOT NULL DEFAULT '0',
  `price` int NOT NULL DEFAULT '0',
  `offprice` int NOT NULL DEFAULT '0',
  `type` int NOT NULL DEFAULT '0',
  `tag` varchar(32) NOT NULL DEFAULT '0',
  `starttime` int NOT NULL DEFAULT '0',
  `endtime` int NOT NULL DEFAULT '0',
  `limitcount` int NOT NULL DEFAULT '0',
  `count` int NOT NULL DEFAULT '0',
  `vipLimit` int NOT NULL DEFAULT '0',
  `value` int NOT NULL DEFAULT '0',
  `exvalue` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `shop_discount`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `shop_discount` (
  `id` int NOT NULL AUTO_INCREMENT,
  `awardID1` mediumtext,
  `awardID2` mediumtext,
  `awardID3` mediumtext,
  `awardNum1` mediumtext,
  `awardNum2` mediumtext,
  `awardNum3` mediumtext,
  `awardType1` mediumtext,
  `awardType2` mediumtext,
  `awardType3` mediumtext,
  `def` mediumtext,
  `discount` mediumtext,
  `msg` mediumtext,
  `name` mediumtext,
  `srcPrice` mediumtext,
  `type` mediumtext,
  `vip0` mediumtext,
  `vip1` mediumtext,
  `vip10` mediumtext,
  `vip11` mediumtext,
  `vip12` mediumtext,
  `vip13` mediumtext,
  `vip14` mediumtext,
  `vip15` mediumtext,
  `vip2` mediumtext,
  `vip3` mediumtext,
  `vip4` mediumtext,
  `vip5` mediumtext,
  `vip6` mediumtext,
  `vip7` mediumtext,
  `vip8` mediumtext,
  `vip9` mediumtext,
  `vipLimit` mediumtext,
  `weekdayInfo` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `shop_discount_save`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `shop_discount_save` (
  `id` int NOT NULL AUTO_INCREMENT,
  `discount_Id` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `shop_mystery`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `shop_mystery` (
  `id` int NOT NULL AUTO_INCREMENT,
  `exvalue` mediumtext,
  `item` mediumtext,
  `num` mediumtext,
  `price` mediumtext,
  `rate1` mediumtext,
  `rate2` mediumtext,
  `rate3` mediumtext,
  `rate4` mediumtext,
  `rate5` mediumtext,
  `rate6` mediumtext,
  `rate7` mediumtext,
  `rate8` mediumtext,
  `rate9` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `shop_yaoshi`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `shop_yaoshi` (
  `id` int NOT NULL AUTO_INCREMENT,
  `item` mediumtext,
  `num` mediumtext,
  `price` mediumtext,
  `rate1` mediumtext,
  `rate10` mediumtext,
  `rate11` mediumtext,
  `rate12` mediumtext,
  `rate2` mediumtext,
  `rate3` mediumtext,
  `rate4` mediumtext,
  `rate5` mediumtext,
  `rate6` mediumtext,
  `rate7` mediumtext,
  `rate8` mediumtext,
  `rate9` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `sig_log`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `sig_log` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `skill`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `skill` (
  `id` int NOT NULL AUTO_INCREMENT,
  `CD` mediumtext,
  `des` mediumtext,
  `learnLevel` mediumtext,
  `name` mediumtext,
  `xiang` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `skill_levelup`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `skill_levelup` (
  `id` int NOT NULL AUTO_INCREMENT,
  `money` mediumtext,
  `QianNeng` mediumtext,
  `skillId` mediumtext,
  `skillLevel` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `source`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `source` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `start`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `start` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `stream`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `stream` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `strtoddiyfp`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `strtoddiyfp` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `taohuageng_config`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `taohuageng_config` (
  `id` int NOT NULL AUTO_INCREMENT,
  `material_id` int NOT NULL DEFAULT '0',
  `material_per_num` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `template`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `template` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `text`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `text` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `that`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `that` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `tongtianta`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `tongtianta` (
  `id` int NOT NULL AUTO_INCREMENT,
  `_1` mediumtext,
  `roleId` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `transform`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `transform` (
  `id` int NOT NULL AUTO_INCREMENT,
  `attr_type1` mediumtext,
  `attr_type2` mediumtext,
  `attr_type3` mediumtext,
  `attr_type4` mediumtext,
  `attr_type5` mediumtext,
  `attr_type6` mediumtext,
  `attr_type7` mediumtext,
  `attr_type8` mediumtext,
  `attr_value1` mediumtext,
  `attr_value2` mediumtext,
  `attr_value3` mediumtext,
  `attr_value4` mediumtext,
  `attr_value5` mediumtext,
  `attr_value6` mediumtext,
  `attr_value7` mediumtext,
  `attr_value8` mediumtext,
  `item_id` mediumtext,
  `last_time` mediumtext,
  `monster_id` mediumtext,
  `monster_name` mediumtext,
  `name` mediumtext,
  `quality` mediumtext,
  `target_type` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `user_award`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `user_award` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `user_info`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `user_info` (
  `id` int NOT NULL AUTO_INCREMENT,
  `bd_money` mediumtext,
  `binding` mediumtext,
  `del_test_award` mediumtext,
  `money` mediumtext,
  `name` mediumtext,
  `password` mediumtext,
  `personal_id` mediumtext,
  `personal_name` mediumtext,
  `phone_state` mediumtext,
  `role0` mediumtext,
  `role1` mediumtext,
  `role2` mediumtext,
  `role3` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `user_info1`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `user_info1` (
  `id` int NOT NULL AUTO_INCREMENT,
  `bd_money` mediumtext,
  `binding` mediumtext,
  `del_test_award` mediumtext,
  `money` mediumtext,
  `name` mediumtext,
  `password` mediumtext,
  `personal_id` mediumtext,
  `personal_name` mediumtext,
  `phone_state` mediumtext,
  `role0` mediumtext,
  `role1` mediumtext,
  `role2` mediumtext,
  `role3` mediumtext,
  `ad` int NOT NULL DEFAULT '0',
  `del_time0` int NOT NULL DEFAULT '0',
  `type` int NOT NULL DEFAULT '0',
  `reg_time` int NOT NULL DEFAULT '0',
  `mobile_type` varchar(32) NOT NULL DEFAULT '',
  `mobile_info` varchar(255) NOT NULL DEFAULT '',
  `new_user` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `user_record_log`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `user_record_log` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `value`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `value` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `vip_def`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `vip_def` (
  `id` int NOT NULL AUTO_INCREMENT,
  `arenabuy` mediumtext,
  `arenatz` mediumtext,
  `awardn1` mediumtext,
  `awardn2` mediumtext,
  `awardn3` mediumtext,
  `awardt1` mediumtext,
  `awardt2` mediumtext,
  `awardt3` mediumtext,
  `bossbuy` mediumtext,
  `bosstz` mediumtext,
  `fengshen_shilian` mediumtext,
  `fxdown` mediumtext,
  `fxexp` mediumtext,
  `jingbi_tree` mediumtext,
  `jingyan_tree` mediumtext,
  `lingqi` mediumtext,
  `neidan_tree` mediumtext,
  `offline` mediumtext,
  `openshop` mediumtext,
  `sweep_copy` mediumtext,
  `vip` mediumtext,
  `yaoqianshu` mediumtext,
  `yaoqianshu2` mediumtext,
  `yuanbao` mediumtext,
  `yuanbao_tree` mediumtext,
  `zhongzhi` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `white_ip`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `white_ip` (
  `id` int NOT NULL AUTO_INCREMENT,
  `comment` mediumtext,
  `ip` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `xianyuan_card`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `xianyuan_card` (
  `id` int NOT NULL AUTO_INCREMENT,
  `chapter_info` mediumtext,
  `des` mediumtext,
  `isnotice` mediumtext,
  `item_id` mediumtext,
  `name` mediumtext,
  `pic` mediumtext,
  `quality` mediumtext,
  `single_odds` mediumtext,
  `ten_odds` mediumtext,
  `xy_value` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `xianyuan_chapter`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `xianyuan_chapter` (
  `id` int NOT NULL AUTO_INCREMENT,
  `attr_type1` mediumtext,
  `attr_type2` mediumtext,
  `attr_type3` mediumtext,
  `attr_type4` mediumtext,
  `attr_value1` mediumtext,
  `attr_value2` mediumtext,
  `attr_value3` mediumtext,
  `attr_value4` mediumtext,
  `des` mediumtext,
  `name` mediumtext,
  `need_card1` mediumtext,
  `need_card2` mediumtext,
  `need_card3` mediumtext,
  `need_card4` mediumtext,
  `need_card5` mediumtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `xin_shi`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `xin_shi` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `zha_dan_info`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `zha_dan_info` (
  `id` int NOT NULL AUTO_INCREMENT,
  `type` int NOT NULL DEFAULT '0',
  `award` int NOT NULL DEFAULT '0',
  `num` int NOT NULL DEFAULT '0',
  `petQt` int NOT NULL DEFAULT '0',
  `petQtLv` int NOT NULL DEFAULT '0',
  `rate` int NOT NULL DEFAULT '0',
  `isJinPin` int NOT NULL DEFAULT '0',
  `isShow` int NOT NULL DEFAULT '0',
  `notice` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `zha_dan_log`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `zha_dan_log` (
  `id` int NOT NULL AUTO_INCREMENT,
  `data` text,
  `time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;


-- Local-only first-charge UI fallback. Do not treat these as production rewards.
INSERT INTO `hd_peizhi_info`
  (`type`,`yb`,`count`,`lv`,`idx`,`cdTime`,`price`,`count_ext8`,`lastTime_ext32`,`zhenying1_name`,`zhenying2_name`,`water_cz`,`bug_cz`,`step1_cz`,`step2_cz`)
SELECT 29,60,1,0,1,0,6,0,0,'','',0,0,0,0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `hd_peizhi_info` WHERE `type`=29);

INSERT INTO `huodong_award`
  (`type`,`idx`,`YB`,`award1`,`num1`,`petQt1`,`petQtLv1`,`award2`,`num2`,`petQt2`,`petQtLv2`,`award3`,`num3`,`petQt3`,`petQtLv3`,`award4`,`num4`,`petQt4`,`petQtLv4`,`award5`,`num5`,`petQt5`,`petQtLv5`,`award6`,`num6`,`petQt6`,`petQtLv6`,`idx2`,`idx3`)
SELECT 29,1,0,60002,19,5,1,1001,10,0,0,837,10,0,0,60000,100000,0,0,60001,500,0,0,0,0,0,0,0,0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `huodong_award` WHERE `type`=29 AND `idx`=1);

-- Trading-house initialization requires one baseline exchange-rate row.
INSERT INTO `jiaoyi_gold_yuzhi` (`id`,`gold`,`time`)
SELECT 1,30000,NOW() FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `jiaoyi_gold_yuzhi`);

-- Keep the local trading-house feature in its legacy default state.
INSERT INTO `function_switch` (`id`,`function_type`,`switch_state`)
SELECT 1,1,1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `function_switch` WHERE `function_type`=1);