-- Auto-generated local fallback schema. Do not use for production.
SET NAMES utf8;
SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE IF NOT EXISTS `admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `Allows` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `another` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `arena_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `arena_paihang` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `arena_paihang_save` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `arena_robot` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `array` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ASCII` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `back_libao_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `bad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `bang_pai` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `bang_pai_guard` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `bang_pai_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `bang_pai_mission` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `award1` MEDIUMTEXT NULL,
  `award2` MEDIUMTEXT NULL,
  `desc_str` MEDIUMTEXT NULL,
  `name` MEDIUMTEXT NULL,
  `num1` MEDIUMTEXT NULL,
  `num2` MEDIUMTEXT NULL,
  `type` MEDIUMTEXT NULL,
  `value` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `bang_pai_plant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `bang_pai_role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `bang_pai_seed_config` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `gainItem` MEDIUMTEXT NULL,
  `gainType` MEDIUMTEXT NULL,
  `gainValue` MEDIUMTEXT NULL,
  `itemId` MEDIUMTEXT NULL,
  `killBugLimit` MEDIUMTEXT NULL,
  `killBugTimeGap` MEDIUMTEXT NULL,
  `pic1` MEDIUMTEXT NULL,
  `pic2` MEDIUMTEXT NULL,
  `pic3` MEDIUMTEXT NULL,
  `price` MEDIUMTEXT NULL,
  `priceType` MEDIUMTEXT NULL,
  `ripeTimeGap` MEDIUMTEXT NULL,
  `stealNum` MEDIUMTEXT NULL,
  `treeName` MEDIUMTEXT NULL,
  `wateringLimit` MEDIUMTEXT NULL,
  `wateringReduce` MEDIUMTEXT NULL,
  `wateringTimeGap` MEDIUMTEXT NULL,
  `witheredTimeGap` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `bang_pai_shangxian` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `bang_pai_shangxian_mode` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `gain_type1` MEDIUMTEXT NULL,
  `gain_type2` MEDIUMTEXT NULL,
  `gain_value1` MEDIUMTEXT NULL,
  `gain_value2` MEDIUMTEXT NULL,
  `loss_type` MEDIUMTEXT NULL,
  `loss_value` MEDIUMTEXT NULL,
  `name` MEDIUMTEXT NULL,
  `succ_ratio` MEDIUMTEXT NULL,
  `type` MEDIUMTEXT NULL,
  `use_item_id1` MEDIUMTEXT NULL,
  `use_item_id2` MEDIUMTEXT NULL,
  `use_item_num1` MEDIUMTEXT NULL,
  `use_item_num2` MEDIUMTEXT NULL,
  `vip_limit` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `bang_tiaozhan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `bangzhan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `bangzhan_role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `black_ip` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `Boost` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `chat_ignore_word` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `chat_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `chong_fanli` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `chongzhi` MEDIUMTEXT NULL,
  `fanli` MEDIUMTEXT NULL,
  `first_fanli` MEDIUMTEXT NULL,
  `first_item_id` MEDIUMTEXT NULL,
  `first_item_num` MEDIUMTEXT NULL,
  `item_id` MEDIUMTEXT NULL,
  `item_num` MEDIUMTEXT NULL,
  `pic_idx` MEDIUMTEXT NULL,
  `show_idx` MEDIUMTEXT NULL,
  `type` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `chongfanli` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `config` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `consideration` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `cz_complete` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ad` MEDIUMTEXT NULL,
  `card_num` MEDIUMTEXT NULL,
  `err_msg` MEDIUMTEXT NULL,
  `is_deal` MEDIUMTEXT NULL,
  `money` MEDIUMTEXT NULL,
  `role_id` MEDIUMTEXT NULL,
  `role_level` MEDIUMTEXT NULL,
  `role_name` MEDIUMTEXT NULL,
  `server_id` MEDIUMTEXT NULL,
  `state` MEDIUMTEXT NULL,
  `time` MEDIUMTEXT NULL,
  `type` MEDIUMTEXT NULL,
  `user_id` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `cz_notice` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `is_first` MEDIUMTEXT NULL,
  `money` MEDIUMTEXT NULL,
  `msg` MEDIUMTEXT NULL,
  `user_id` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `cz_to_other_reward` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `dailysign` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `_1` MEDIUMTEXT NULL,
  `award_num` MEDIUMTEXT NULL,
  `award_type` MEDIUMTEXT NULL,
  `award_value` MEDIUMTEXT NULL,
  `day_idx` MEDIUMTEXT NULL,
  `mon_type` MEDIUMTEXT NULL,
  `vip_lv` MEDIUMTEXT NULL,
  `vip_multiple` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `defining` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `dengjilibao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `goods1` MEDIUMTEXT NULL,
  `goods2` MEDIUMTEXT NULL,
  `goods3` MEDIUMTEXT NULL,
  `level` MEDIUMTEXT NULL,
  `num1` MEDIUMTEXT NULL,
  `num2` MEDIUMTEXT NULL,
  `num3` MEDIUMTEXT NULL,
  `value1` MEDIUMTEXT NULL,
  `value2` MEDIUMTEXT NULL,
  `value3` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `Doxygen` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `Encoding` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `equip` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `fabao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `fanli_jihuoma` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `festival_award` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `festival_box` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `festival_record` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `fight_cg` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fightMsg` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `fight_playback` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `flower_config` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `buy_type` MEDIUMTEXT NULL,
  `item_id` MEDIUMTEXT NULL,
  `mei_li` MEDIUMTEXT NULL,
  `price` MEDIUMTEXT NULL,
  `qin_mi` MEDIUMTEXT NULL,
  `rank` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `footprint_config` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `buy_type` MEDIUMTEXT NULL,
  `desc` MEDIUMTEXT NULL,
  `name` MEDIUMTEXT NULL,
  `price` MEDIUMTEXT NULL,
  `rank` MEDIUMTEXT NULL,
  `time` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `friend_list` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_id` INT NOT NULL,
  `friend_info` TEXT NOT NULL,
  `apply_list` TEXT NOT NULL,
  `black_list` TEXT NOT NULL,
  UNIQUE KEY `role_id` (`role_id`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `friend_list_save` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_id` INT NOT NULL,
  `friend_info` TEXT NOT NULL,
  `apply_list` TEXT NOT NULL,
  `black_list` TEXT NOT NULL,
  UNIQUE KEY `role_id` (`role_id`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `fuben_richang` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `condes1` MEDIUMTEXT NULL,
  `condes2` MEDIUMTEXT NULL,
  `condes3` MEDIUMTEXT NULL,
  `condes4` MEDIUMTEXT NULL,
  `desc_ratio` MEDIUMTEXT NULL,
  `desc_ratio1` MEDIUMTEXT NULL,
  `desc_title` MEDIUMTEXT NULL,
  `enterlimit` MEDIUMTEXT NULL,
  `extdata8` MEDIUMTEXT NULL,
  `fuben_index` MEDIUMTEXT NULL,
  `isShow` MEDIUMTEXT NULL,
  `level` MEDIUMTEXT NULL,
  `lvup_type1` MEDIUMTEXT NULL,
  `lvup_type2` MEDIUMTEXT NULL,
  `lvup_type3` MEDIUMTEXT NULL,
  `lvup_type4` MEDIUMTEXT NULL,
  `lvup_value1` MEDIUMTEXT NULL,
  `lvup_value2` MEDIUMTEXT NULL,
  `lvup_value3` MEDIUMTEXT NULL,
  `lvup_value4` MEDIUMTEXT NULL,
  `mobs` MEDIUMTEXT NULL,
  `mop_time` MEDIUMTEXT NULL,
  `name` MEDIUMTEXT NULL,
  `reward1` MEDIUMTEXT NULL,
  `reward2` MEDIUMTEXT NULL,
  `reward3` MEDIUMTEXT NULL,
  `reward4` MEDIUMTEXT NULL,
  `sceneId` MEDIUMTEXT NULL,
  `tili` MEDIUMTEXT NULL,
  `type` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `function_switch` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `game_scene` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fight_step` MEDIUMTEXT NULL,
  `fight_type` MEDIUMTEXT NULL,
  `group_id` MEDIUMTEXT NULL,
  `height` MEDIUMTEXT NULL,
  `map_id` MEDIUMTEXT NULL,
  `monster` MEDIUMTEXT NULL,
  `name` MEDIUMTEXT NULL,
  `show_type` MEDIUMTEXT NULL,
  `width` MEDIUMTEXT NULL,
  `world_trans` MEDIUMTEXT NULL,
  `x` MEDIUMTEXT NULL,
  `y` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `GenericReader` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `GenericValue` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `global_variable` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `happening` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `hd_7ridenglu` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `hd_bang_goods` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `award1` MEDIUMTEXT NULL,
  `pic` MEDIUMTEXT NULL,
  `score1_get` MEDIUMTEXT NULL,
  `score1_give` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `hd_chou_record` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `hd_exchange_drop` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `hd_exchange_list` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `hd_paihang_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `hd_paihang_record` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `hd_peizhi_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bug_cz` MEDIUMTEXT NULL,
  `cdTime` MEDIUMTEXT NULL,
  `count` MEDIUMTEXT NULL,
  `count_ext8` MEDIUMTEXT NULL,
  `idx` MEDIUMTEXT NULL,
  `lastTime_ext32` MEDIUMTEXT NULL,
  `lv` MEDIUMTEXT NULL,
  `price` MEDIUMTEXT NULL,
  `step1_cz` MEDIUMTEXT NULL,
  `step2_cz` MEDIUMTEXT NULL,
  `type` MEDIUMTEXT NULL,
  `water_cz` MEDIUMTEXT NULL,
  `yb` MEDIUMTEXT NULL,
  `zhenying1_name` MEDIUMTEXT NULL,
  `zhenying2_name` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `hd_rand_award` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `hd_save_data` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `hd_show_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `help` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `huan_haoli_drop` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ext8_idx` MEDIUMTEXT NULL,
  `item_id` MEDIUMTEXT NULL,
  `limit_num` MEDIUMTEXT NULL,
  `name` MEDIUMTEXT NULL,
  `type` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `huodong_award` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `award1` MEDIUMTEXT NULL,
  `award2` MEDIUMTEXT NULL,
  `award3` MEDIUMTEXT NULL,
  `award4` MEDIUMTEXT NULL,
  `award5` MEDIUMTEXT NULL,
  `award6` MEDIUMTEXT NULL,
  `idx` MEDIUMTEXT NULL,
  `idx2` MEDIUMTEXT NULL,
  `idx3` MEDIUMTEXT NULL,
  `num1` MEDIUMTEXT NULL,
  `num2` MEDIUMTEXT NULL,
  `num3` MEDIUMTEXT NULL,
  `num4` MEDIUMTEXT NULL,
  `num5` MEDIUMTEXT NULL,
  `num6` MEDIUMTEXT NULL,
  `petQt1` MEDIUMTEXT NULL,
  `petQt2` MEDIUMTEXT NULL,
  `petQt3` MEDIUMTEXT NULL,
  `petQt4` MEDIUMTEXT NULL,
  `petQt5` MEDIUMTEXT NULL,
  `petQt6` MEDIUMTEXT NULL,
  `petQtLv1` MEDIUMTEXT NULL,
  `petQtLv2` MEDIUMTEXT NULL,
  `petQtLv3` MEDIUMTEXT NULL,
  `petQtLv4` MEDIUMTEXT NULL,
  `petQtLv5` MEDIUMTEXT NULL,
  `petQtLv6` MEDIUMTEXT NULL,
  `type` MEDIUMTEXT NULL,
  `YB` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `huodong_exchange` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `award1` MEDIUMTEXT NULL,
  `award2` MEDIUMTEXT NULL,
  `award3` MEDIUMTEXT NULL,
  `award4` MEDIUMTEXT NULL,
  `award5` MEDIUMTEXT NULL,
  `award6` MEDIUMTEXT NULL,
  `exchange_num_limit` MEDIUMTEXT NULL,
  `idx` MEDIUMTEXT NULL,
  `isShow` MEDIUMTEXT NULL,
  `material_1` MEDIUMTEXT NULL,
  `material_1_num` MEDIUMTEXT NULL,
  `material_2` MEDIUMTEXT NULL,
  `material_2_num` MEDIUMTEXT NULL,
  `material_3` MEDIUMTEXT NULL,
  `material_3_num` MEDIUMTEXT NULL,
  `material_4` MEDIUMTEXT NULL,
  `material_4_num` MEDIUMTEXT NULL,
  `material_5` MEDIUMTEXT NULL,
  `material_5_num` MEDIUMTEXT NULL,
  `material_is_or` MEDIUMTEXT NULL,
  `num1` MEDIUMTEXT NULL,
  `num2` MEDIUMTEXT NULL,
  `num3` MEDIUMTEXT NULL,
  `num4` MEDIUMTEXT NULL,
  `num5` MEDIUMTEXT NULL,
  `num6` MEDIUMTEXT NULL,
  `petQt1` MEDIUMTEXT NULL,
  `petQt2` MEDIUMTEXT NULL,
  `petQt3` MEDIUMTEXT NULL,
  `petQt4` MEDIUMTEXT NULL,
  `petQt5` MEDIUMTEXT NULL,
  `petQt6` MEDIUMTEXT NULL,
  `petQtLv1` MEDIUMTEXT NULL,
  `petQtLv2` MEDIUMTEXT NULL,
  `petQtLv3` MEDIUMTEXT NULL,
  `petQtLv4` MEDIUMTEXT NULL,
  `petQtLv5` MEDIUMTEXT NULL,
  `petQtLv6` MEDIUMTEXT NULL,
  `saveExt8` MEDIUMTEXT NULL,
  `type` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `huodong_exp` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `exp1` MEDIUMTEXT NULL,
  `exp10` MEDIUMTEXT NULL,
  `exp100` MEDIUMTEXT NULL,
  `exp101` MEDIUMTEXT NULL,
  `exp102` MEDIUMTEXT NULL,
  `exp103` MEDIUMTEXT NULL,
  `exp104` MEDIUMTEXT NULL,
  `exp105` MEDIUMTEXT NULL,
  `exp106` MEDIUMTEXT NULL,
  `exp107` MEDIUMTEXT NULL,
  `exp108` MEDIUMTEXT NULL,
  `exp109` MEDIUMTEXT NULL,
  `exp11` MEDIUMTEXT NULL,
  `exp110` MEDIUMTEXT NULL,
  `exp111` MEDIUMTEXT NULL,
  `exp112` MEDIUMTEXT NULL,
  `exp113` MEDIUMTEXT NULL,
  `exp114` MEDIUMTEXT NULL,
  `exp115` MEDIUMTEXT NULL,
  `exp116` MEDIUMTEXT NULL,
  `exp117` MEDIUMTEXT NULL,
  `exp118` MEDIUMTEXT NULL,
  `exp119` MEDIUMTEXT NULL,
  `exp12` MEDIUMTEXT NULL,
  `exp120` MEDIUMTEXT NULL,
  `exp121` MEDIUMTEXT NULL,
  `exp122` MEDIUMTEXT NULL,
  `exp123` MEDIUMTEXT NULL,
  `exp124` MEDIUMTEXT NULL,
  `exp125` MEDIUMTEXT NULL,
  `exp126` MEDIUMTEXT NULL,
  `exp127` MEDIUMTEXT NULL,
  `exp128` MEDIUMTEXT NULL,
  `exp129` MEDIUMTEXT NULL,
  `exp13` MEDIUMTEXT NULL,
  `exp130` MEDIUMTEXT NULL,
  `exp14` MEDIUMTEXT NULL,
  `exp15` MEDIUMTEXT NULL,
  `exp16` MEDIUMTEXT NULL,
  `exp17` MEDIUMTEXT NULL,
  `exp18` MEDIUMTEXT NULL,
  `exp19` MEDIUMTEXT NULL,
  `exp2` MEDIUMTEXT NULL,
  `exp20` MEDIUMTEXT NULL,
  `exp21` MEDIUMTEXT NULL,
  `exp22` MEDIUMTEXT NULL,
  `exp23` MEDIUMTEXT NULL,
  `exp24` MEDIUMTEXT NULL,
  `exp25` MEDIUMTEXT NULL,
  `exp26` MEDIUMTEXT NULL,
  `exp27` MEDIUMTEXT NULL,
  `exp28` MEDIUMTEXT NULL,
  `exp29` MEDIUMTEXT NULL,
  `exp3` MEDIUMTEXT NULL,
  `exp30` MEDIUMTEXT NULL,
  `exp31` MEDIUMTEXT NULL,
  `exp32` MEDIUMTEXT NULL,
  `exp33` MEDIUMTEXT NULL,
  `exp34` MEDIUMTEXT NULL,
  `exp35` MEDIUMTEXT NULL,
  `exp36` MEDIUMTEXT NULL,
  `exp37` MEDIUMTEXT NULL,
  `exp38` MEDIUMTEXT NULL,
  `exp39` MEDIUMTEXT NULL,
  `exp4` MEDIUMTEXT NULL,
  `exp40` MEDIUMTEXT NULL,
  `exp41` MEDIUMTEXT NULL,
  `exp42` MEDIUMTEXT NULL,
  `exp43` MEDIUMTEXT NULL,
  `exp44` MEDIUMTEXT NULL,
  `exp45` MEDIUMTEXT NULL,
  `exp46` MEDIUMTEXT NULL,
  `exp47` MEDIUMTEXT NULL,
  `exp48` MEDIUMTEXT NULL,
  `exp49` MEDIUMTEXT NULL,
  `exp5` MEDIUMTEXT NULL,
  `exp50` MEDIUMTEXT NULL,
  `exp51` MEDIUMTEXT NULL,
  `exp52` MEDIUMTEXT NULL,
  `exp53` MEDIUMTEXT NULL,
  `exp54` MEDIUMTEXT NULL,
  `exp55` MEDIUMTEXT NULL,
  `exp56` MEDIUMTEXT NULL,
  `exp57` MEDIUMTEXT NULL,
  `exp58` MEDIUMTEXT NULL,
  `exp59` MEDIUMTEXT NULL,
  `exp6` MEDIUMTEXT NULL,
  `exp60` MEDIUMTEXT NULL,
  `exp61` MEDIUMTEXT NULL,
  `exp62` MEDIUMTEXT NULL,
  `exp63` MEDIUMTEXT NULL,
  `exp64` MEDIUMTEXT NULL,
  `exp65` MEDIUMTEXT NULL,
  `exp66` MEDIUMTEXT NULL,
  `exp67` MEDIUMTEXT NULL,
  `exp68` MEDIUMTEXT NULL,
  `exp69` MEDIUMTEXT NULL,
  `exp7` MEDIUMTEXT NULL,
  `exp70` MEDIUMTEXT NULL,
  `exp71` MEDIUMTEXT NULL,
  `exp72` MEDIUMTEXT NULL,
  `exp73` MEDIUMTEXT NULL,
  `exp74` MEDIUMTEXT NULL,
  `exp75` MEDIUMTEXT NULL,
  `exp76` MEDIUMTEXT NULL,
  `exp77` MEDIUMTEXT NULL,
  `exp78` MEDIUMTEXT NULL,
  `exp79` MEDIUMTEXT NULL,
  `exp8` MEDIUMTEXT NULL,
  `exp80` MEDIUMTEXT NULL,
  `exp81` MEDIUMTEXT NULL,
  `exp82` MEDIUMTEXT NULL,
  `exp83` MEDIUMTEXT NULL,
  `exp84` MEDIUMTEXT NULL,
  `exp85` MEDIUMTEXT NULL,
  `exp86` MEDIUMTEXT NULL,
  `exp87` MEDIUMTEXT NULL,
  `exp88` MEDIUMTEXT NULL,
  `exp89` MEDIUMTEXT NULL,
  `exp9` MEDIUMTEXT NULL,
  `exp90` MEDIUMTEXT NULL,
  `exp91` MEDIUMTEXT NULL,
  `exp92` MEDIUMTEXT NULL,
  `exp93` MEDIUMTEXT NULL,
  `exp94` MEDIUMTEXT NULL,
  `exp95` MEDIUMTEXT NULL,
  `exp96` MEDIUMTEXT NULL,
  `exp97` MEDIUMTEXT NULL,
  `exp98` MEDIUMTEXT NULL,
  `exp99` MEDIUMTEXT NULL,
  `name` MEDIUMTEXT NULL,
  `type` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `huodong_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `day` MEDIUMTEXT NULL,
  `endHour` MEDIUMTEXT NULL,
  `endTime` MEDIUMTEXT NULL,
  `isShow` MEDIUMTEXT NULL,
  `name` MEDIUMTEXT NULL,
  `pic` MEDIUMTEXT NULL,
  `showIdx` MEDIUMTEXT NULL,
  `startHour` MEDIUMTEXT NULL,
  `startTime` MEDIUMTEXT NULL,
  `type` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `huodong_time` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `input` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `integer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `item_score_exchange` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `item_template` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `add_qixue` MEDIUMTEXT NULL,
  `add_sudu` MEDIUMTEXT NULL,
  `baoji` MEDIUMTEXT NULL,
  `des` MEDIUMTEXT NULL,
  `equip_pos` MEDIUMTEXT NULL,
  `fafang` MEDIUMTEXT NULL,
  `fangyu` MEDIUMTEXT NULL,
  `gongji` MEDIUMTEXT NULL,
  `item_from` MEDIUMTEXT NULL,
  `item_source` MEDIUMTEXT NULL,
  `jiage` MEDIUMTEXT NULL,
  `kangbao` MEDIUMTEXT NULL,
  `level` MEDIUMTEXT NULL,
  `mingzhong` MEDIUMTEXT NULL,
  `mod` MEDIUMTEXT NULL,
  `naijiu` MEDIUMTEXT NULL,
  `name` MEDIUMTEXT NULL,
  `pic` MEDIUMTEXT NULL,
  `quality` MEDIUMTEXT NULL,
  `sell` MEDIUMTEXT NULL,
  `sex` MEDIUMTEXT NULL,
  `shanbi` MEDIUMTEXT NULL,
  `sort_priority` MEDIUMTEXT NULL,
  `type` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `iterator` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `jiaoyi_gold_yuzhi` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `jiaoyi_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `jiaoyi_record` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `jihuoma` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `jihuoma_fa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `jump_point` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `face` MEDIUMTEXT NULL,
  `from_scene` MEDIUMTEXT NULL,
  `from_x` MEDIUMTEXT NULL,
  `from_y` MEDIUMTEXT NULL,
  `to_scene` MEDIUMTEXT NULL,
  `to_x` MEDIUMTEXT NULL,
  `to_y` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `kf_config` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `kuafu_1vs1_final_data` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `kuafu_1vs1_final_vote` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `kuafu_1vs1_preliminary` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `kuafu_paihang` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `leitai_paiming` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `level_rank` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `mei_li_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `mei_li_paihang` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `mei_li_send_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `Microsoft` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `mijing_boss_ratio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `mobai` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `money_giftbag_huodong` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `money_giftbag_pay` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `monster` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `attack` MEDIUMTEXT NULL,
  `attackRatio` MEDIUMTEXT NULL,
  `attackStepRatio` MEDIUMTEXT NULL,
  `defence` MEDIUMTEXT NULL,
  `defenceRatio` MEDIUMTEXT NULL,
  `defenceStepRatio` MEDIUMTEXT NULL,
  `drop_item` MEDIUMTEXT NULL,
  `exp` MEDIUMTEXT NULL,
  `huanhua_material` MEDIUMTEXT NULL,
  `huanhuaPetId` MEDIUMTEXT NULL,
  `inTuJian` MEDIUMTEXT NULL,
  `isJueXingPet` MEDIUMTEXT NULL,
  `juexingPetId` MEDIUMTEXT NULL,
  `max_level` MEDIUMTEXT NULL,
  `max_quality` MEDIUMTEXT NULL,
  `maxHp` MEDIUMTEXT NULL,
  `maxHpRatio` MEDIUMTEXT NULL,
  `maxHpStepRatio` MEDIUMTEXT NULL,
  `min_level` MEDIUMTEXT NULL,
  `min_quality` MEDIUMTEXT NULL,
  `monsterName` MEDIUMTEXT NULL,
  `petName` MEDIUMTEXT NULL,
  `skill` MEDIUMTEXT NULL,
  `skillAttack` MEDIUMTEXT NULL,
  `skillAttackRatio` MEDIUMTEXT NULL,
  `skillAttackStepRatio` MEDIUMTEXT NULL,
  `speed` MEDIUMTEXT NULL,
  `speedRatio` MEDIUMTEXT NULL,
  `speedStepRatio` MEDIUMTEXT NULL,
  `t_drop_item` MEDIUMTEXT NULL,
  `tujianIdx` MEDIUMTEXT NULL,
  `type` MEDIUMTEXT NULL,
  `xiang` MEDIUMTEXT NULL,
  `zizhi` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `monster_boss_distribution` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dropItem` MEDIUMTEXT NULL,
  `face` MEDIUMTEXT NULL,
  `fightPos1` MEDIUMTEXT NULL,
  `fightPos2` MEDIUMTEXT NULL,
  `fightPos3` MEDIUMTEXT NULL,
  `fightPos4` MEDIUMTEXT NULL,
  `fightPos5` MEDIUMTEXT NULL,
  `fightPos6` MEDIUMTEXT NULL,
  `meetDistance` MEDIUMTEXT NULL,
  `name` MEDIUMTEXT NULL,
  `pic` MEDIUMTEXT NULL,
  `pos_x` MEDIUMTEXT NULL,
  `pos_y` MEDIUMTEXT NULL,
  `radius` MEDIUMTEXT NULL,
  `sayContent` MEDIUMTEXT NULL,
  `scale1` MEDIUMTEXT NULL,
  `scale2` MEDIUMTEXT NULL,
  `scale3` MEDIUMTEXT NULL,
  `scale4` MEDIUMTEXT NULL,
  `scale5` MEDIUMTEXT NULL,
  `scale6` MEDIUMTEXT NULL,
  `sceneId` MEDIUMTEXT NULL,
  `step` MEDIUMTEXT NULL,
  `type` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `monster_distribution` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `findPath_x` MEDIUMTEXT NULL,
  `findPath_y` MEDIUMTEXT NULL,
  `max_fightId` MEDIUMTEXT NULL,
  `meetDistance` MEDIUMTEXT NULL,
  `min_fightId` MEDIUMTEXT NULL,
  `monster_id` MEDIUMTEXT NULL,
  `pos` MEDIUMTEXT NULL,
  `radius` MEDIUMTEXT NULL,
  `scene_id` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `mutable` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `name_reg0` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `name_reg1` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `names` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `non` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `notice` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `begin_time` MEDIUMTEXT NULL,
  `end_time` MEDIUMTEXT NULL,
  `msg` MEDIUMTEXT NULL,
  `time_space` MEDIUMTEXT NULL,
  `type` MEDIUMTEXT NULL,
  `type1` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `notice_login` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `npc_instance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `face` MEDIUMTEXT NULL,
  `scene_id` MEDIUMTEXT NULL,
  `show_type` MEDIUMTEXT NULL,
  `template_id` MEDIUMTEXT NULL,
  `x_pos` MEDIUMTEXT NULL,
  `y_pos` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `npc_template` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` MEDIUMTEXT NULL,
  `npc_type` MEDIUMTEXT NULL,
  `picture` MEDIUMTEXT NULL,
  `script` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `old_account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `online_user_num` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `num` MEDIUMTEXT NULL,
  `time` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `operator` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ParseStream` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `plain` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `pointer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `pre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `Predict` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `primary` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `qiang_hongbao_record` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `qin_mi_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `question` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(255) NOT NULL DEFAULT '',
  `answer1` VARCHAR(255) NOT NULL DEFAULT '',
  `answer2` VARCHAR(255) NOT NULL DEFAULT '',
  `answer3` VARCHAR(255) NOT NULL DEFAULT '',
  `answer4` VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `qunxian_paihang` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `randombox_cfg` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `rank_list` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `rank_list_save` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `read` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `Rob` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `role_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `admin` MEDIUMTEXT NULL,
  `bank_item` MEDIUMTEXT NULL,
  `bd_money` MEDIUMTEXT NULL,
  `bitset` MEDIUMTEXT NULL,
  `chat_time` MEDIUMTEXT NULL,
  `exp` MEDIUMTEXT NULL,
  `head` MEDIUMTEXT NULL,
  `hots` MEDIUMTEXT NULL,
  `korea_money_gift` MEDIUMTEXT NULL,
  `kuafu_state` MEDIUMTEXT NULL,
  `level` MEDIUMTEXT NULL,
  `login_time` MEDIUMTEXT NULL,
  `model` MEDIUMTEXT NULL,
  `money` MEDIUMTEXT NULL,
  `mount` MEDIUMTEXT NULL,
  `name` MEDIUMTEXT NULL,
  `package` MEDIUMTEXT NULL,
  `pet` MEDIUMTEXT NULL,
  `pet_equip` MEDIUMTEXT NULL,
  `petZhanDouLi` MEDIUMTEXT NULL,
  `reg_time` MEDIUMTEXT NULL,
  `save_data` MEDIUMTEXT NULL,
  `sex` MEDIUMTEXT NULL,
  `sg_bitset` MEDIUMTEXT NULL,
  `shenqi` MEDIUMTEXT NULL,
  `state` MEDIUMTEXT NULL,
  `title` MEDIUMTEXT NULL,
  `user_book` MEDIUMTEXT NULL,
  `wing` MEDIUMTEXT NULL,
  `xianyuan` MEDIUMTEXT NULL,
  `zhanDouLi` MEDIUMTEXT NULL,
  `zhenfa` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `role_info_transfer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `role_mirror` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `role_simple_list` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `role_simple_list_save` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `role_xiuxian` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `admin` MEDIUMTEXT NULL,
  `bangpai` MEDIUMTEXT NULL,
  `bank_item` MEDIUMTEXT NULL,
  `bank_money` MEDIUMTEXT NULL,
  `bitset` MEDIUMTEXT NULL,
  `bossFightStar` MEDIUMTEXT NULL,
  `chat_channel` MEDIUMTEXT NULL,
  `chat_time` MEDIUMTEXT NULL,
  `collect_npc` MEDIUMTEXT NULL,
  `currency` MEDIUMTEXT NULL,
  `daohang` MEDIUMTEXT NULL,
  `drop_touchitem` MEDIUMTEXT NULL,
  `equipment` MEDIUMTEXT NULL,
  `exp` MEDIUMTEXT NULL,
  `head` MEDIUMTEXT NULL,
  `hots` MEDIUMTEXT NULL,
  `hp` MEDIUMTEXT NULL,
  `jianyu_time` MEDIUMTEXT NULL,
  `level` MEDIUMTEXT NULL,
  `login_time` MEDIUMTEXT NULL,
  `map_id` MEDIUMTEXT NULL,
  `menpai` MEDIUMTEXT NULL,
  `money` MEDIUMTEXT NULL,
  `mount` MEDIUMTEXT NULL,
  `mp` MEDIUMTEXT NULL,
  `mp_gongxian` MEDIUMTEXT NULL,
  `mysteryShop` MEDIUMTEXT NULL,
  `name` MEDIUMTEXT NULL,
  `nextOpenTime` MEDIUMTEXT NULL,
  `open_pack` MEDIUMTEXT NULL,
  `package` MEDIUMTEXT NULL,
  `pet` MEDIUMTEXT NULL,
  `petKaiJia` MEDIUMTEXT NULL,
  `petZhanDouLi` MEDIUMTEXT NULL,
  `pk_time` MEDIUMTEXT NULL,
  `pk_val` MEDIUMTEXT NULL,
  `position` MEDIUMTEXT NULL,
  `qianneng` MEDIUMTEXT NULL,
  `reg_time` MEDIUMTEXT NULL,
  `save_data` MEDIUMTEXT NULL,
  `save_monster` MEDIUMTEXT NULL,
  `save_npc` MEDIUMTEXT NULL,
  `save_val` MEDIUMTEXT NULL,
  `script_double` MEDIUMTEXT NULL,
  `script_timer` MEDIUMTEXT NULL,
  `sex` MEDIUMTEXT NULL,
  `sg_bitset` MEDIUMTEXT NULL,
  `shop` MEDIUMTEXT NULL,
  `skills` MEDIUMTEXT NULL,
  `state` MEDIUMTEXT NULL,
  `tili` MEDIUMTEXT NULL,
  `title` MEDIUMTEXT NULL,
  `use_double_end` MEDIUMTEXT NULL,
  `use_double_type` MEDIUMTEXT NULL,
  `wing` MEDIUMTEXT NULL,
  `wing_zhandouli` MEDIUMTEXT NULL,
  `x_pos` MEDIUMTEXT NULL,
  `xiang` MEDIUMTEXT NULL,
  `y_pos` MEDIUMTEXT NULL,
  `zhanDouLi` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `script_save_role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `server_list` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `shilian_robot` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `shop` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `item` INT NOT NULL DEFAULT 0,
  `price` INT NOT NULL DEFAULT 0,
  `offprice` INT NOT NULL DEFAULT 0,
  `type` INT NOT NULL DEFAULT 0,
  `tag` VARCHAR(32) NOT NULL DEFAULT '0',
  `starttime` INT NOT NULL DEFAULT 0,
  `endtime` INT NOT NULL DEFAULT 0,
  `limitcount` INT NOT NULL DEFAULT 0,
  `count` INT NOT NULL DEFAULT 0,
  `vipLimit` INT NOT NULL DEFAULT 0,
  `value` INT NOT NULL DEFAULT 0,
  `exvalue` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `shop_discount` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `awardID1` MEDIUMTEXT NULL,
  `awardID2` MEDIUMTEXT NULL,
  `awardID3` MEDIUMTEXT NULL,
  `awardNum1` MEDIUMTEXT NULL,
  `awardNum2` MEDIUMTEXT NULL,
  `awardNum3` MEDIUMTEXT NULL,
  `awardType1` MEDIUMTEXT NULL,
  `awardType2` MEDIUMTEXT NULL,
  `awardType3` MEDIUMTEXT NULL,
  `def` MEDIUMTEXT NULL,
  `discount` MEDIUMTEXT NULL,
  `msg` MEDIUMTEXT NULL,
  `name` MEDIUMTEXT NULL,
  `srcPrice` MEDIUMTEXT NULL,
  `type` MEDIUMTEXT NULL,
  `vip0` MEDIUMTEXT NULL,
  `vip1` MEDIUMTEXT NULL,
  `vip10` MEDIUMTEXT NULL,
  `vip11` MEDIUMTEXT NULL,
  `vip12` MEDIUMTEXT NULL,
  `vip13` MEDIUMTEXT NULL,
  `vip14` MEDIUMTEXT NULL,
  `vip15` MEDIUMTEXT NULL,
  `vip2` MEDIUMTEXT NULL,
  `vip3` MEDIUMTEXT NULL,
  `vip4` MEDIUMTEXT NULL,
  `vip5` MEDIUMTEXT NULL,
  `vip6` MEDIUMTEXT NULL,
  `vip7` MEDIUMTEXT NULL,
  `vip8` MEDIUMTEXT NULL,
  `vip9` MEDIUMTEXT NULL,
  `vipLimit` MEDIUMTEXT NULL,
  `weekdayInfo` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `shop_discount_save` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `discount_Id` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `shop_mystery` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `exvalue` MEDIUMTEXT NULL,
  `item` MEDIUMTEXT NULL,
  `num` MEDIUMTEXT NULL,
  `price` MEDIUMTEXT NULL,
  `rate1` MEDIUMTEXT NULL,
  `rate2` MEDIUMTEXT NULL,
  `rate3` MEDIUMTEXT NULL,
  `rate4` MEDIUMTEXT NULL,
  `rate5` MEDIUMTEXT NULL,
  `rate6` MEDIUMTEXT NULL,
  `rate7` MEDIUMTEXT NULL,
  `rate8` MEDIUMTEXT NULL,
  `rate9` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `shop_yaoshi` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `item` MEDIUMTEXT NULL,
  `num` MEDIUMTEXT NULL,
  `price` MEDIUMTEXT NULL,
  `rate1` MEDIUMTEXT NULL,
  `rate10` MEDIUMTEXT NULL,
  `rate11` MEDIUMTEXT NULL,
  `rate12` MEDIUMTEXT NULL,
  `rate2` MEDIUMTEXT NULL,
  `rate3` MEDIUMTEXT NULL,
  `rate4` MEDIUMTEXT NULL,
  `rate5` MEDIUMTEXT NULL,
  `rate6` MEDIUMTEXT NULL,
  `rate7` MEDIUMTEXT NULL,
  `rate8` MEDIUMTEXT NULL,
  `rate9` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `sig_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `skill` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `CD` MEDIUMTEXT NULL,
  `des` MEDIUMTEXT NULL,
  `learnLevel` MEDIUMTEXT NULL,
  `name` MEDIUMTEXT NULL,
  `xiang` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `skill_levelup` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `money` MEDIUMTEXT NULL,
  `QianNeng` MEDIUMTEXT NULL,
  `skillId` MEDIUMTEXT NULL,
  `skillLevel` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `source` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `start` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `stream` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `StrtodDiyFp` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `taohuageng_config` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `template` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `text` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `that` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `tongtianta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `_1` MEDIUMTEXT NULL,
  `roleId` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `transform` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `attr_type1` MEDIUMTEXT NULL,
  `attr_type2` MEDIUMTEXT NULL,
  `attr_type3` MEDIUMTEXT NULL,
  `attr_type4` MEDIUMTEXT NULL,
  `attr_type5` MEDIUMTEXT NULL,
  `attr_type6` MEDIUMTEXT NULL,
  `attr_type7` MEDIUMTEXT NULL,
  `attr_type8` MEDIUMTEXT NULL,
  `attr_value1` MEDIUMTEXT NULL,
  `attr_value2` MEDIUMTEXT NULL,
  `attr_value3` MEDIUMTEXT NULL,
  `attr_value4` MEDIUMTEXT NULL,
  `attr_value5` MEDIUMTEXT NULL,
  `attr_value6` MEDIUMTEXT NULL,
  `attr_value7` MEDIUMTEXT NULL,
  `attr_value8` MEDIUMTEXT NULL,
  `item_id` MEDIUMTEXT NULL,
  `last_time` MEDIUMTEXT NULL,
  `monster_id` MEDIUMTEXT NULL,
  `monster_name` MEDIUMTEXT NULL,
  `name` MEDIUMTEXT NULL,
  `quality` MEDIUMTEXT NULL,
  `target_type` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `user_award` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `user_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bd_money` MEDIUMTEXT NULL,
  `binding` MEDIUMTEXT NULL,
  `del_test_award` MEDIUMTEXT NULL,
  `money` MEDIUMTEXT NULL,
  `name` MEDIUMTEXT NULL,
  `password` MEDIUMTEXT NULL,
  `personal_id` MEDIUMTEXT NULL,
  `personal_name` MEDIUMTEXT NULL,
  `phone_state` MEDIUMTEXT NULL,
  `role0` MEDIUMTEXT NULL,
  `role1` MEDIUMTEXT NULL,
  `role2` MEDIUMTEXT NULL,
  `role3` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `user_info1` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bd_money` MEDIUMTEXT NULL,
  `binding` MEDIUMTEXT NULL,
  `del_test_award` MEDIUMTEXT NULL,
  `money` MEDIUMTEXT NULL,
  `name` MEDIUMTEXT NULL,
  `password` MEDIUMTEXT NULL,
  `personal_id` MEDIUMTEXT NULL,
  `personal_name` MEDIUMTEXT NULL,
  `phone_state` MEDIUMTEXT NULL,
  `role0` MEDIUMTEXT NULL,
  `role1` MEDIUMTEXT NULL,
  `role2` MEDIUMTEXT NULL,
  `role3` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `user_record_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `Value` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `vip_def` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `arenabuy` MEDIUMTEXT NULL,
  `arenatz` MEDIUMTEXT NULL,
  `awardn1` MEDIUMTEXT NULL,
  `awardn2` MEDIUMTEXT NULL,
  `awardn3` MEDIUMTEXT NULL,
  `awardt1` MEDIUMTEXT NULL,
  `awardt2` MEDIUMTEXT NULL,
  `awardt3` MEDIUMTEXT NULL,
  `bossbuy` MEDIUMTEXT NULL,
  `bosstz` MEDIUMTEXT NULL,
  `fengshen_shilian` MEDIUMTEXT NULL,
  `fxdown` MEDIUMTEXT NULL,
  `fxexp` MEDIUMTEXT NULL,
  `jingbi_tree` MEDIUMTEXT NULL,
  `jingyan_tree` MEDIUMTEXT NULL,
  `lingqi` MEDIUMTEXT NULL,
  `neidan_tree` MEDIUMTEXT NULL,
  `offline` MEDIUMTEXT NULL,
  `openshop` MEDIUMTEXT NULL,
  `sweep_copy` MEDIUMTEXT NULL,
  `vip` MEDIUMTEXT NULL,
  `yaoqianshu` MEDIUMTEXT NULL,
  `yaoqianshu2` MEDIUMTEXT NULL,
  `yuanbao` MEDIUMTEXT NULL,
  `yuanbao_tree` MEDIUMTEXT NULL,
  `zhongzhi` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `white_ip` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comment` MEDIUMTEXT NULL,
  `ip` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `xianyuan_card` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `chapter_info` MEDIUMTEXT NULL,
  `des` MEDIUMTEXT NULL,
  `isnotice` MEDIUMTEXT NULL,
  `item_id` MEDIUMTEXT NULL,
  `name` MEDIUMTEXT NULL,
  `pic` MEDIUMTEXT NULL,
  `quality` MEDIUMTEXT NULL,
  `single_odds` MEDIUMTEXT NULL,
  `ten_odds` MEDIUMTEXT NULL,
  `xy_value` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `xianyuan_chapter` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `attr_type1` MEDIUMTEXT NULL,
  `attr_type2` MEDIUMTEXT NULL,
  `attr_type3` MEDIUMTEXT NULL,
  `attr_type4` MEDIUMTEXT NULL,
  `attr_value1` MEDIUMTEXT NULL,
  `attr_value2` MEDIUMTEXT NULL,
  `attr_value3` MEDIUMTEXT NULL,
  `attr_value4` MEDIUMTEXT NULL,
  `des` MEDIUMTEXT NULL,
  `name` MEDIUMTEXT NULL,
  `need_card1` MEDIUMTEXT NULL,
  `need_card2` MEDIUMTEXT NULL,
  `need_card3` MEDIUMTEXT NULL,
  `need_card4` MEDIUMTEXT NULL,
  `need_card5` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `xin_shi` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `zha_dan_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `zha_dan_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

SET FOREIGN_KEY_CHECKS=1;
