local WelfareActivityDef = {}

WelfareActivityDef.Type = {
	MeiRiShouChong = 1, --每日首充
	RechargeGift = 3,  --充值送礼
	ConsumptionGift = 4, --累计消费
	ZuiQiangShenChongBang = 13,  --最强神宠榜
	XianJiaQiangHuaBang = 14,  --仙甲强化榜
	DengJiChongCiBang = 15,  --等级冲刺赛
	QunXianZhanLiBang = 16,  --群仙战力榜
	XinFuChongZhiBang = 17,  --新服充值榜
	NationalDayGift = 21, --国庆送礼活动
	NationDayCollectWord = 38, --国庆集字活动

	ZaDan = 20,  --砸蛋
	ZaDan2 = 92,  --砸蛋2
	SevenDaysChargeTag = 22,--7日充值领奖
	ShenJiYuYiBang = 33,--神级羽翼榜
	PetDiscount = 84,--神将折扣
	XianHuaBang = 85,--鲜花排行榜
	------------------------------------------
	GetTiLi = 101,--领取体力
}

return WelfareActivityDef

-- HD_HAOHUALIBAO = 1,		// 豪华礼包
-- 	HD_MEIRIGONGZI = 2,		// 每日工资
-- 	HD_MIANFEIZUOQI = 3,	// 免费坐骑
-- 	HD_ZAIXIANLINGHAOLI = 4,// 在线领好礼
-- 	HD_LIANXUDENGLUJIANGLI = 5,	// 7日登陆奖励
-- 	HD_CHENGZHANGLIBAO = 6,	// 成长礼包
-- 	HD_SHENGJILIBAO = 7,	// 升级礼包
-- 	HD_SHOUCHONG = 9,		// 首充
-- 	HD_TAOCAN = 10,			// 付费套餐
-- 	HD_DENGLULIBAO = 11,	// 连续登陆奖励 登陆礼包
-- 	HD_CHONGZHISONGLI = 12,	// 充值送礼
-- 	HD_KAIFUCHONGJI = 13,	// 开服冲级赛
-- 	HD_XINFUZHANLIBANG = 14,// 新服战力榜
-- 	HD_XIANCHONGDASHOUJI = 15,		// 仙宠大收集
-- 	HD_QIANGZHUANGLINGHAOLI = 16,	// 强装领好礼
-- 	HD_YAO_QIAN_SHU = 17,	// 摇钱树
-- 	HD_MEIRI_SHOUCHONG = 18, //每日首充
-- 	HD_JIERI_LIBAO = 19, //节日礼包
-- 	HD_LEI_JI_CHONGZHI = 20,	// 累计充值
-- 	HD_LEI_JI_XIAO_FEI = 21,	// 累计消费
-- 	HD_ZHENGDIANZAIXIAN = 22,	//整点在线礼包
-- 	HD_CHONGZHIFANYB = 23, //每日大返利
-- 	HD_HONGLICHONGZHI = 24, //红利大放送 充值
-- 	HD_HONGLIXIAOFEI = 25,  //红利大放送 消费
-- 	HD_SHEN_CHONG_BANG = 26,	// 最强神宠榜
-- 	HD_EQUIP_QIANG_HUA = 27,	// 仙甲强化榜
-- 	HD_ROLE_LEVEL_BANG = 28,	// 等级冲刺榜
-- 	HD_ZHAN_LI_BANG = 29,		// 群仙战力榜
-- 	HD_CHONG_ZHI_BANG = 30,		// 新服充值榜
-- 	HD_QIANGHUA_KUANGHUAN = 31,		// 强化狂欢礼
-- 	HD_SHENGJIE_LETIAN = 32,		// 升阶乐翻天
-- 	HD_ZHA_DAN = 33,		// 砸蛋
-- 	HD_FESTIVAL = 34,		// 节日
-- 	HD_LIANXU_CHONGZHI_ORI = 35,// 连续充值-普通
-- 	HD_LIANXU_CHONGZHI_DELUXE = 36,// 连续充值-豪华
-- 	HD_JIERI_LIBAO2 = 37, //节日礼包2
-- 	HD_LEI_JI_CHONGZHI2 = 38,	//累计充值2
-- 	HD_LEI_JI_XIAO_FEI2 = 39,	//累计消费2
-- 	HD_CHONGZHIFANYB2 = 40,		//每日大返利2
-- 	HD_CHONGZHIFANYB3 = 41,		//每日大返利3
-- 	HD_CICHONG = 42,			// 次充
-- 	HD_CHONGZHIFANYB4 = 43,		//每日大返利4
-- 	HD_CHONGZHIFANYB5 = 44,		//每日大返利5
-- 	HD_WING_BANG = 45,			//神级羽翼榜
-- 	HD_HONGLICHONGZHI_RMB = 46, //红利大放送 充值 RMB
-- 	HD_HONGLI_JIFEN = 47, //红利积分
-- 	HD_JIJIN_FANLI = 48, //基金返利
-- 	HD_DAOJUHUISHOU = 49,	//道具回收
-- 	HD_MEIRI_HUAN_HAOLI = 50, //每日换好礼
-- 	HD_XIAN_SHI_CHOU = 51, //限时抽活动
-- 	HD_CHONGZHIFANYB6 = 52,		//每日大返利6
-- 	HD_CHONGZHIFANYB7 = 53,		//每日大返利7
-- 	HD_CHONGZHIFANYB8 = 54,		//每日大返利8
-- 	HD_CHONGZHIFANYB9 = 55,		//每日大返利9
-- 	HD_CHONGZHIFANYB10 = 56,	//每日大返利10
-- 	HD_HONGLI_JIFEN2 = 57, //红利积分2
-- 	HD_HONGLI_JIFEN3 = 58, //红利积分3
-- 	HD_HONGLI_JIFEN4 = 59, //红利积分4
-- 	HD_HONGLI_JIFEN5 = 60, //红利积分5
-- 	HD_HONGLICHONGZHI2 = 61, //红利大放送 充值2
-- 	HD_HONGLICHONGZHI3 = 62, //红利大放送 充值3
-- 	HD_HONGLICHONGZHI4 = 63, //红利大放送 充值4
-- 	HD_HONGLICHONGZHI5 = 64, //红利大放送 充值5
-- 	HD_HONGLIXIAOFEI2 = 65,  //红利大放送 消费2
-- 	HD_HONGLIXIAOFEI3 = 66,  //红利大放送 消费3
-- 	HD_HONGLIXIAOFEI4 = 67,  //红利大放送 消费4
-- 	HD_HONGLIXIAOFEI5 = 68,  //红利大放送 消费5
-- 	HD_JIJIN_FANLI2 = 69, //基金返利2
-- 	HD_JIJIN_FANLI3 = 70, //基金返利3
-- 	HD_MARRIAGE_BANG = 71,//婚姻排行榜
-- 	HD_XINCHUN_HAPPY = 72,//新春快乐
-- 	HD_ZHENYING_PK = 73,// 阵营PK
-- 	HD_QIANG_HONGBAO = 74,// 抢红包
-- 	HD_HUOYUE_TASK = 75,// 活跃任务
-- 	HD_MEIRI_XIAOHAO1 = 76,	// 每日消耗1
-- 	HD_MEIRI_XIAOHAO2 = 77,	// 每日消耗2
-- 	HD_MEIRI_XIAOHAO3 = 78,	// 每日消耗3
-- 	HD_MEIRI_XIAOHAO4 = 79,	// 每日消耗4
-- 	HD_MEIRI_XIAOHAO5 = 80,	// 每日消耗5